import { Command } from 'commander';
import pc from 'picocolors';
import { existsSync, watch, writeFileSync, mkdirSync } from 'node:fs';
import type { FSWatcher } from 'node:fs';
import { join } from 'node:path';
import { execSync, spawn } from 'node:child_process';
import type { ChildProcess } from 'node:child_process';
import { discoverPipelines } from '../discovery.js';
import { runSynth } from './synth.js';

// ── Command registration ────────────────────────────────────────────

export function registerDevCommand(program: Command): void {
  program
    .command('dev')
    .description('Start development mode with file watching')
    .option('-p, --pipeline <name>', 'Watch a specific pipeline')
    .option('--no-docker', 'Skip starting Docker Compose environment')
    .option('--port <port>', 'Kafka broker port', '9092')
    .action(async (opts: { pipeline?: string; docker: boolean; port: string }) => {
      await runDev(opts);
    });
}

// ── Dev server state ────────────────────────────────────────────────

interface DevState {
  projectDir: string;
  pipeline?: string;
  docker: boolean;
  port: string;
  watchers: FSWatcher[];
  dockerProcess: ChildProcess | null;
  shuttingDown: boolean;
}

// ── Docker Compose generation ───────────────────────────────────────

function generateDockerCompose(port: string): string {
  return `# Generated by isotope dev — do not edit
services:
  kafka:
    image: apache/kafka:3.9.0
    ports:
      - "${port}:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:${port}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: isotope-dev-cluster-001
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  runtime:
    image: isotope-runtime:latest
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./dist:/plans:ro
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PLAN_DIR: /plans
`;
}

// ── Dev logic ───────────────────────────────────────────────────────

export async function runDev(opts: {
  pipeline?: string;
  docker: boolean;
  port: string;
  projectDir?: string;
}): Promise<void> {
  const projectDir = opts.projectDir ?? process.cwd();

  const state: DevState = {
    projectDir,
    pipeline: opts.pipeline,
    docker: opts.docker,
    port: opts.port,
    watchers: [],
    dockerProcess: null,
    shuttingDown: false,
  };

  console.log(pc.bold('\n  isotope dev\n'));

  // Run initial synthesis
  console.log(pc.dim('Running initial synthesis...\n'));
  await runSynth({
    pipeline: state.pipeline,
    outdir: 'dist',
    projectDir,
  });

  // Start Docker Compose if requested
  if (state.docker) {
    await startDocker(state);
  }

  // Set up file watchers
  setupWatchers(state);

  // Set up keyboard shortcuts
  setupKeyboard(state);

  printHelp();

  // Keep process alive
  await new Promise<void>((resolve) => {
    const check = (): void => {
      if (state.shuttingDown) {
        resolve();
      } else {
        setTimeout(check, 500);
      }
    };
    check();
  });
}

// ── Docker Compose ──────────────────────────────────────────────────

async function startDocker(state: DevState): Promise<void> {
  const composePath = join(state.projectDir, 'docker-compose.yml');

  // Generate docker-compose.yml if it doesn't exist
  if (!existsSync(composePath)) {
    console.log(pc.dim('Generating docker-compose.yml...'));
    const compose = generateDockerCompose(state.port);
    writeFileSync(composePath, compose, 'utf-8');
  }

  console.log(pc.dim(`Starting Docker Compose environment...`));

  try {
    const child = spawn('docker', ['compose', 'up', '-d'], {
      cwd: state.projectDir,
      stdio: 'pipe',
    });

    child.on('error', () => {
      console.log(pc.yellow('Docker not available. Skipping Docker Compose start.'));
      console.log(pc.dim('Use --no-docker to suppress this warning.\n'));
    });

    state.dockerProcess = child;

    // Wait briefly for startup
    await new Promise((resolve) => setTimeout(resolve, 2000));
    console.log(pc.green(`Kafka broker: localhost:${state.port}\n`));
  } catch {
    console.log(pc.yellow('Failed to start Docker Compose. Continuing without it.'));
  }
}

// ── File watchers ───────────────────────────────────────────────────

function setupWatchers(state: DevState): void {
  const dirs = ['pipelines'];
  const configFile = join(state.projectDir, 'isotope.config.ts');

  for (const dir of dirs) {
    const watchDir = join(state.projectDir, dir);
    if (!existsSync(watchDir)) continue;

    try {
      const watcher = watch(watchDir, { recursive: true }, (event, filename) => {
        if (state.shuttingDown || !filename) return;

        console.log(pc.dim(`\n[${new Date().toLocaleTimeString()}] Change detected: ${dir}/${filename}`));
        onFileChange(state);
      });

      state.watchers.push(watcher);
      console.log(pc.dim(`  Watching ${dir}/`));
    } catch {
      // Directory might not exist or watch not supported
    }
  }

  // Watch config file
  if (existsSync(configFile)) {
    try {
      const watcher = watch(configFile, () => {
        if (state.shuttingDown) return;
        console.log(pc.dim(`\n[${new Date().toLocaleTimeString()}] Change detected: isotope.config.ts`));
        onFileChange(state);
      });
      state.watchers.push(watcher);
      console.log(pc.dim(`  Watching isotope.config.ts`));
    } catch {
      // Watch not supported
    }
  }

  console.log('');
}

let debounceTimer: ReturnType<typeof setTimeout> | null = null;

function onFileChange(state: DevState): void {
  if (debounceTimer) clearTimeout(debounceTimer);

  debounceTimer = setTimeout(async () => {
    console.log(pc.dim('Re-synthesizing...\n'));
    await runSynth({
      pipeline: state.pipeline,
      outdir: 'dist',
      projectDir: state.projectDir,
    });
  }, 300);
}

// ── Keyboard shortcuts ──────────────────────────────────────────────

function setupKeyboard(state: DevState): void {
  if (!process.stdin.isTTY) return;

  process.stdin.setRawMode(true);
  process.stdin.resume();
  process.stdin.setEncoding('utf-8');

  process.stdin.on('data', async (key: string) => {
    if (state.shuttingDown) return;

    switch (key) {
      case 'r':
        console.log(pc.dim('\n[manual] Re-synthesizing...\n'));
        await runSynth({
          pipeline: state.pipeline,
          outdir: 'dist',
          projectDir: state.projectDir,
        });
        break;

      case 'q':
      case '\u0003': // Ctrl+C
        await shutdown(state);
        break;

      case 'h':
      case '?':
        printHelp();
        break;
    }
  });
}

function printHelp(): void {
  console.log(pc.dim('  Keyboard shortcuts:'));
  console.log(pc.dim('    r  re-synthesize'));
  console.log(pc.dim('    h  show help'));
  console.log(pc.dim('    q  quit'));
  console.log('');
}

// ── Shutdown ────────────────────────────────────────────────────────

async function shutdown(state: DevState): Promise<void> {
  state.shuttingDown = true;
  console.log(pc.dim('\nShutting down...'));

  // Close file watchers
  for (const watcher of state.watchers) {
    watcher.close();
  }

  // Stop Docker Compose
  if (state.dockerProcess) {
    try {
      execSync('docker compose down', {
        cwd: state.projectDir,
        stdio: 'pipe',
      });
    } catch {
      // Best-effort cleanup
    }
  }

  // Restore terminal
  if (process.stdin.isTTY) {
    process.stdin.setRawMode(false);
  }

  process.exit(0);
}
