// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: isotope/v1/operators.proto

package isotopev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KafkaSourceConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Topic            string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	BootstrapServers string                 `protobuf:"bytes,2,opt,name=bootstrap_servers,json=bootstrapServers,proto3" json:"bootstrap_servers,omitempty"`
	Format           string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"` // "json" | "csv"
	Schema           *Schema                `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	StartupMode      string                 `protobuf:"bytes,5,opt,name=startup_mode,json=startupMode,proto3" json:"startup_mode,omitempty"` // "earliest-offset" | "latest-offset" | "group-offsets"
	ConsumerGroup    string                 `protobuf:"bytes,6,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KafkaSourceConfig) Reset() {
	*x = KafkaSourceConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaSourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaSourceConfig) ProtoMessage() {}

func (x *KafkaSourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaSourceConfig.ProtoReflect.Descriptor instead.
func (*KafkaSourceConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{0}
}

func (x *KafkaSourceConfig) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *KafkaSourceConfig) GetBootstrapServers() string {
	if x != nil {
		return x.BootstrapServers
	}
	return ""
}

func (x *KafkaSourceConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *KafkaSourceConfig) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *KafkaSourceConfig) GetStartupMode() string {
	if x != nil {
		return x.StartupMode
	}
	return ""
}

func (x *KafkaSourceConfig) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

type GeneratorSourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *Schema                `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	RowsPerSecond int64                  `protobuf:"varint,2,opt,name=rows_per_second,json=rowsPerSecond,proto3" json:"rows_per_second,omitempty"`
	MaxRows       int64                  `protobuf:"varint,3,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"` // 0 = unlimited
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratorSourceConfig) Reset() {
	*x = GeneratorSourceConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratorSourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratorSourceConfig) ProtoMessage() {}

func (x *GeneratorSourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratorSourceConfig.ProtoReflect.Descriptor instead.
func (*GeneratorSourceConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratorSourceConfig) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *GeneratorSourceConfig) GetRowsPerSecond() int64 {
	if x != nil {
		return x.RowsPerSecond
	}
	return 0
}

func (x *GeneratorSourceConfig) GetMaxRows() int64 {
	if x != nil {
		return x.MaxRows
	}
	return 0
}

type KafkaSinkConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Topic            string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	BootstrapServers string                 `protobuf:"bytes,2,opt,name=bootstrap_servers,json=bootstrapServers,proto3" json:"bootstrap_servers,omitempty"`
	Format           string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"` // "json" | "csv"
	KeyBy            []string               `protobuf:"bytes,4,rep,name=key_by,json=keyBy,proto3" json:"key_by,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KafkaSinkConfig) Reset() {
	*x = KafkaSinkConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaSinkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaSinkConfig) ProtoMessage() {}

func (x *KafkaSinkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaSinkConfig.ProtoReflect.Descriptor instead.
func (*KafkaSinkConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{2}
}

func (x *KafkaSinkConfig) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *KafkaSinkConfig) GetBootstrapServers() string {
	if x != nil {
		return x.BootstrapServers
	}
	return ""
}

func (x *KafkaSinkConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *KafkaSinkConfig) GetKeyBy() []string {
	if x != nil {
		return x.KeyBy
	}
	return nil
}

type ConsoleSinkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxRows       int32                  `protobuf:"varint,1,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"` // 0 = unlimited
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleSinkConfig) Reset() {
	*x = ConsoleSinkConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleSinkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleSinkConfig) ProtoMessage() {}

func (x *ConsoleSinkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleSinkConfig.ProtoReflect.Descriptor instead.
func (*ConsoleSinkConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{3}
}

func (x *ConsoleSinkConfig) GetMaxRows() int32 {
	if x != nil {
		return x.MaxRows
	}
	return 0
}

type FilterConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw SQL condition (e.g., "amount > 100 AND country = 'US'").
	ConditionSql  string `protobuf:"bytes,1,opt,name=condition_sql,json=conditionSql,proto3" json:"condition_sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterConfig) Reset() {
	*x = FilterConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterConfig) ProtoMessage() {}

func (x *FilterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterConfig.ProtoReflect.Descriptor instead.
func (*FilterConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{4}
}

func (x *FilterConfig) GetConditionSql() string {
	if x != nil {
		return x.ConditionSql
	}
	return ""
}

type MapConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column mappings: output_name -> SQL expression.
	Columns       map[string]string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapConfig) Reset() {
	*x = MapConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapConfig) ProtoMessage() {}

func (x *MapConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapConfig.ProtoReflect.Descriptor instead.
func (*MapConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{5}
}

func (x *MapConfig) GetColumns() map[string]string {
	if x != nil {
		return x.Columns
	}
	return nil
}

type FlatMapConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The array column to unnest.
	UnnestColumn string `protobuf:"bytes,1,opt,name=unnest_column,json=unnestColumn,proto3" json:"unnest_column,omitempty"`
	// Output schema for the unnested rows.
	OutputFields  []*SchemaField `protobuf:"bytes,2,rep,name=output_fields,json=outputFields,proto3" json:"output_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatMapConfig) Reset() {
	*x = FlatMapConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatMapConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatMapConfig) ProtoMessage() {}

func (x *FlatMapConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatMapConfig.ProtoReflect.Descriptor instead.
func (*FlatMapConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{6}
}

func (x *FlatMapConfig) GetUnnestColumn() string {
	if x != nil {
		return x.UnnestColumn
	}
	return ""
}

func (x *FlatMapConfig) GetOutputFields() []*SchemaField {
	if x != nil {
		return x.OutputFields
	}
	return nil
}

type AggregateConfig struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupBy []string               `protobuf:"bytes,1,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	// Aggregate expressions: output_name -> SQL expression (e.g., "SUM(amount)").
	Select        map[string]string `protobuf:"bytes,2,rep,name=select,proto3" json:"select,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateConfig) Reset() {
	*x = AggregateConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateConfig) ProtoMessage() {}

func (x *AggregateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateConfig.ProtoReflect.Descriptor instead.
func (*AggregateConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{7}
}

func (x *AggregateConfig) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *AggregateConfig) GetSelect() map[string]string {
	if x != nil {
		return x.Select
	}
	return nil
}

type RenameConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mapping of old_name -> new_name.
	Columns       map[string]string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameConfig) Reset() {
	*x = RenameConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameConfig) ProtoMessage() {}

func (x *RenameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameConfig.ProtoReflect.Descriptor instead.
func (*RenameConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{8}
}

func (x *RenameConfig) GetColumns() map[string]string {
	if x != nil {
		return x.Columns
	}
	return nil
}

type DropConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropConfig) Reset() {
	*x = DropConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropConfig) ProtoMessage() {}

func (x *DropConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropConfig.ProtoReflect.Descriptor instead.
func (*DropConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{9}
}

func (x *DropConfig) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

type CastConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column name -> target type.
	Columns       map[string]*SchemaField `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastConfig) Reset() {
	*x = CastConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastConfig) ProtoMessage() {}

func (x *CastConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastConfig.ProtoReflect.Descriptor instead.
func (*CastConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{10}
}

func (x *CastConfig) GetColumns() map[string]*SchemaField {
	if x != nil {
		return x.Columns
	}
	return nil
}

type CoalesceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column name -> SQL expression.
	Columns       map[string]string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoalesceConfig) Reset() {
	*x = CoalesceConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoalesceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoalesceConfig) ProtoMessage() {}

func (x *CoalesceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoalesceConfig.ProtoReflect.Descriptor instead.
func (*CoalesceConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{11}
}

func (x *CoalesceConfig) GetColumns() map[string]string {
	if x != nil {
		return x.Columns
	}
	return nil
}

type AddFieldConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column name -> SQL expression.
	Columns map[string]string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional type hints for the added columns.
	Types         map[string]*SchemaField `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFieldConfig) Reset() {
	*x = AddFieldConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFieldConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFieldConfig) ProtoMessage() {}

func (x *AddFieldConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFieldConfig.ProtoReflect.Descriptor instead.
func (*AddFieldConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{12}
}

func (x *AddFieldConfig) GetColumns() map[string]string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *AddFieldConfig) GetTypes() map[string]*SchemaField {
	if x != nil {
		return x.Types
	}
	return nil
}

type UnionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnionConfig) Reset() {
	*x = UnionConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionConfig) ProtoMessage() {}

func (x *UnionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionConfig.ProtoReflect.Descriptor instead.
func (*UnionConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{13}
}

type RouteBranch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SQL condition for this branch.
	ConditionSql string `protobuf:"bytes,1,opt,name=condition_sql,json=conditionSql,proto3" json:"condition_sql,omitempty"`
	// Operator ID of the first operator in this branch.
	TargetOperator string `protobuf:"bytes,2,opt,name=target_operator,json=targetOperator,proto3" json:"target_operator,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteBranch) Reset() {
	*x = RouteBranch{}
	mi := &file_isotope_v1_operators_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteBranch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteBranch) ProtoMessage() {}

func (x *RouteBranch) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteBranch.ProtoReflect.Descriptor instead.
func (*RouteBranch) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{14}
}

func (x *RouteBranch) GetConditionSql() string {
	if x != nil {
		return x.ConditionSql
	}
	return ""
}

func (x *RouteBranch) GetTargetOperator() string {
	if x != nil {
		return x.TargetOperator
	}
	return ""
}

type RouteConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Branches []*RouteBranch         `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	// Operator ID for unmatched rows (optional).
	DefaultOperator string `protobuf:"bytes,2,opt,name=default_operator,json=defaultOperator,proto3" json:"default_operator,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteConfig) Reset() {
	*x = RouteConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConfig) ProtoMessage() {}

func (x *RouteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConfig.ProtoReflect.Descriptor instead.
func (*RouteConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{15}
}

func (x *RouteConfig) GetBranches() []*RouteBranch {
	if x != nil {
		return x.Branches
	}
	return nil
}

func (x *RouteConfig) GetDefaultOperator() string {
	if x != nil {
		return x.DefaultOperator
	}
	return ""
}

type DeduplicateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []string               `protobuf:"bytes,1,rep,name=key,proto3" json:"key,omitempty"`
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Keep          string                 `protobuf:"bytes,3,opt,name=keep,proto3" json:"keep,omitempty"` // "first" | "last"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeduplicateConfig) Reset() {
	*x = DeduplicateConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeduplicateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeduplicateConfig) ProtoMessage() {}

func (x *DeduplicateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeduplicateConfig.ProtoReflect.Descriptor instead.
func (*DeduplicateConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{16}
}

func (x *DeduplicateConfig) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeduplicateConfig) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *DeduplicateConfig) GetKeep() string {
	if x != nil {
		return x.Keep
	}
	return ""
}

type TopNConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionBy   []string               `protobuf:"bytes,1,rep,name=partition_by,json=partitionBy,proto3" json:"partition_by,omitempty"`
	OrderBy       map[string]string      `protobuf:"bytes,2,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // column -> "ASC" | "DESC"
	N             int32                  `protobuf:"varint,3,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopNConfig) Reset() {
	*x = TopNConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopNConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNConfig) ProtoMessage() {}

func (x *TopNConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNConfig.ProtoReflect.Descriptor instead.
func (*TopNConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{17}
}

func (x *TopNConfig) GetPartitionBy() []string {
	if x != nil {
		return x.PartitionBy
	}
	return nil
}

func (x *TopNConfig) GetOrderBy() map[string]string {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *TopNConfig) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type TumbleWindowConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          string                 `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`                               // e.g., "5 MINUTE"
	TimeColumn    string                 `protobuf:"bytes,2,opt,name=time_column,json=timeColumn,proto3" json:"time_column,omitempty"` // The column to window on.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TumbleWindowConfig) Reset() {
	*x = TumbleWindowConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TumbleWindowConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TumbleWindowConfig) ProtoMessage() {}

func (x *TumbleWindowConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TumbleWindowConfig.ProtoReflect.Descriptor instead.
func (*TumbleWindowConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{18}
}

func (x *TumbleWindowConfig) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *TumbleWindowConfig) GetTimeColumn() string {
	if x != nil {
		return x.TimeColumn
	}
	return ""
}

type SlideWindowConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          string                 `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	Slide         string                 `protobuf:"bytes,2,opt,name=slide,proto3" json:"slide,omitempty"`
	TimeColumn    string                 `protobuf:"bytes,3,opt,name=time_column,json=timeColumn,proto3" json:"time_column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlideWindowConfig) Reset() {
	*x = SlideWindowConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlideWindowConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlideWindowConfig) ProtoMessage() {}

func (x *SlideWindowConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlideWindowConfig.ProtoReflect.Descriptor instead.
func (*SlideWindowConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{19}
}

func (x *SlideWindowConfig) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *SlideWindowConfig) GetSlide() string {
	if x != nil {
		return x.Slide
	}
	return ""
}

func (x *SlideWindowConfig) GetTimeColumn() string {
	if x != nil {
		return x.TimeColumn
	}
	return ""
}

type SessionWindowConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gap           string                 `protobuf:"bytes,1,opt,name=gap,proto3" json:"gap,omitempty"`
	TimeColumn    string                 `protobuf:"bytes,2,opt,name=time_column,json=timeColumn,proto3" json:"time_column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionWindowConfig) Reset() {
	*x = SessionWindowConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionWindowConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionWindowConfig) ProtoMessage() {}

func (x *SessionWindowConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionWindowConfig.ProtoReflect.Descriptor instead.
func (*SessionWindowConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{20}
}

func (x *SessionWindowConfig) GetGap() string {
	if x != nil {
		return x.Gap
	}
	return ""
}

func (x *SessionWindowConfig) GetTimeColumn() string {
	if x != nil {
		return x.TimeColumn
	}
	return ""
}

type HashJoinConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConditionSql  string                 `protobuf:"bytes,1,opt,name=condition_sql,json=conditionSql,proto3" json:"condition_sql,omitempty"` // e.g., "a.id = b.id"
	JoinType      string                 `protobuf:"bytes,2,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"`             // "inner" | "left" | "right" | "full" | "anti" | "semi"
	StateTtl      string                 `protobuf:"bytes,3,opt,name=state_ttl,json=stateTtl,proto3" json:"state_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashJoinConfig) Reset() {
	*x = HashJoinConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashJoinConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashJoinConfig) ProtoMessage() {}

func (x *HashJoinConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashJoinConfig.ProtoReflect.Descriptor instead.
func (*HashJoinConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{21}
}

func (x *HashJoinConfig) GetConditionSql() string {
	if x != nil {
		return x.ConditionSql
	}
	return ""
}

func (x *HashJoinConfig) GetJoinType() string {
	if x != nil {
		return x.JoinType
	}
	return ""
}

func (x *HashJoinConfig) GetStateTtl() string {
	if x != nil {
		return x.StateTtl
	}
	return ""
}

type TemporalJoinConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConditionSql  string                 `protobuf:"bytes,1,opt,name=condition_sql,json=conditionSql,proto3" json:"condition_sql,omitempty"`
	AsOf          string                 `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalJoinConfig) Reset() {
	*x = TemporalJoinConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalJoinConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalJoinConfig) ProtoMessage() {}

func (x *TemporalJoinConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalJoinConfig.ProtoReflect.Descriptor instead.
func (*TemporalJoinConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{22}
}

func (x *TemporalJoinConfig) GetConditionSql() string {
	if x != nil {
		return x.ConditionSql
	}
	return ""
}

func (x *TemporalJoinConfig) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

type LookupJoinConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ConditionSql  string                 `protobuf:"bytes,3,opt,name=condition_sql,json=conditionSql,proto3" json:"condition_sql,omitempty"`
	Select        map[string]string      `protobuf:"bytes,4,rep,name=select,proto3" json:"select,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Async         *LookupAsyncConfig     `protobuf:"bytes,5,opt,name=async,proto3" json:"async,omitempty"`
	Cache         *LookupCacheConfig     `protobuf:"bytes,6,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupJoinConfig) Reset() {
	*x = LookupJoinConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupJoinConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupJoinConfig) ProtoMessage() {}

func (x *LookupJoinConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupJoinConfig.ProtoReflect.Descriptor instead.
func (*LookupJoinConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{23}
}

func (x *LookupJoinConfig) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *LookupJoinConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LookupJoinConfig) GetConditionSql() string {
	if x != nil {
		return x.ConditionSql
	}
	return ""
}

func (x *LookupJoinConfig) GetSelect() map[string]string {
	if x != nil {
		return x.Select
	}
	return nil
}

func (x *LookupJoinConfig) GetAsync() *LookupAsyncConfig {
	if x != nil {
		return x.Async
	}
	return nil
}

func (x *LookupJoinConfig) GetCache() *LookupCacheConfig {
	if x != nil {
		return x.Cache
	}
	return nil
}

type LookupAsyncConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Capacity      int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Timeout       string                 `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupAsyncConfig) Reset() {
	*x = LookupAsyncConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupAsyncConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAsyncConfig) ProtoMessage() {}

func (x *LookupAsyncConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAsyncConfig.ProtoReflect.Descriptor instead.
func (*LookupAsyncConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{24}
}

func (x *LookupAsyncConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *LookupAsyncConfig) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *LookupAsyncConfig) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type LookupCacheConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "lru"
	MaxRows       int64                  `protobuf:"varint,2,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"`
	Ttl           string                 `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupCacheConfig) Reset() {
	*x = LookupCacheConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupCacheConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupCacheConfig) ProtoMessage() {}

func (x *LookupCacheConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupCacheConfig.ProtoReflect.Descriptor instead.
func (*LookupCacheConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{25}
}

func (x *LookupCacheConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LookupCacheConfig) GetMaxRows() int64 {
	if x != nil {
		return x.MaxRows
	}
	return 0
}

func (x *LookupCacheConfig) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

type IntervalJoinConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConditionSql  string                 `protobuf:"bytes,1,opt,name=condition_sql,json=conditionSql,proto3" json:"condition_sql,omitempty"`
	IntervalFrom  string                 `protobuf:"bytes,2,opt,name=interval_from,json=intervalFrom,proto3" json:"interval_from,omitempty"`
	IntervalTo    string                 `protobuf:"bytes,3,opt,name=interval_to,json=intervalTo,proto3" json:"interval_to,omitempty"`
	JoinType      string                 `protobuf:"bytes,4,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"` // "inner" | "left" | "right" | "full"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntervalJoinConfig) Reset() {
	*x = IntervalJoinConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntervalJoinConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntervalJoinConfig) ProtoMessage() {}

func (x *IntervalJoinConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntervalJoinConfig.ProtoReflect.Descriptor instead.
func (*IntervalJoinConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{26}
}

func (x *IntervalJoinConfig) GetConditionSql() string {
	if x != nil {
		return x.ConditionSql
	}
	return ""
}

func (x *IntervalJoinConfig) GetIntervalFrom() string {
	if x != nil {
		return x.IntervalFrom
	}
	return ""
}

func (x *IntervalJoinConfig) GetIntervalTo() string {
	if x != nil {
		return x.IntervalTo
	}
	return ""
}

func (x *IntervalJoinConfig) GetJoinType() string {
	if x != nil {
		return x.JoinType
	}
	return ""
}

type RawSQLConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawSQLConfig) Reset() {
	*x = RawSQLConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawSQLConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawSQLConfig) ProtoMessage() {}

func (x *RawSQLConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawSQLConfig.ProtoReflect.Descriptor instead.
func (*RawSQLConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{27}
}

func (x *RawSQLConfig) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type MatchRecognizeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionBy   []string               `protobuf:"bytes,1,rep,name=partition_by,json=partitionBy,proto3" json:"partition_by,omitempty"`
	OrderBy       map[string]string      `protobuf:"bytes,2,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Define        map[string]string      `protobuf:"bytes,4,rep,name=define,proto3" json:"define,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Measures      map[string]string      `protobuf:"bytes,5,rep,name=measures,proto3" json:"measures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AfterMatch    string                 `protobuf:"bytes,6,opt,name=after_match,json=afterMatch,proto3" json:"after_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRecognizeConfig) Reset() {
	*x = MatchRecognizeConfig{}
	mi := &file_isotope_v1_operators_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRecognizeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRecognizeConfig) ProtoMessage() {}

func (x *MatchRecognizeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_operators_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRecognizeConfig.ProtoReflect.Descriptor instead.
func (*MatchRecognizeConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_operators_proto_rawDescGZIP(), []int{28}
}

func (x *MatchRecognizeConfig) GetPartitionBy() []string {
	if x != nil {
		return x.PartitionBy
	}
	return nil
}

func (x *MatchRecognizeConfig) GetOrderBy() map[string]string {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *MatchRecognizeConfig) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *MatchRecognizeConfig) GetDefine() map[string]string {
	if x != nil {
		return x.Define
	}
	return nil
}

func (x *MatchRecognizeConfig) GetMeasures() map[string]string {
	if x != nil {
		return x.Measures
	}
	return nil
}

func (x *MatchRecognizeConfig) GetAfterMatch() string {
	if x != nil {
		return x.AfterMatch
	}
	return ""
}

var File_isotope_v1_operators_proto protoreflect.FileDescriptor

const file_isotope_v1_operators_proto_rawDesc = "" +
	"\n" +
	"\x1aisotope/v1/operators.proto\x12\n" +
	"isotope.v1\x1a\x17isotope/v1/schema.proto\"\xe4\x01\n" +
	"\x11KafkaSourceConfig\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12+\n" +
	"\x11bootstrap_servers\x18\x02 \x01(\tR\x10bootstrapServers\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12*\n" +
	"\x06schema\x18\x04 \x01(\v2\x12.isotope.v1.SchemaR\x06schema\x12!\n" +
	"\fstartup_mode\x18\x05 \x01(\tR\vstartupMode\x12%\n" +
	"\x0econsumer_group\x18\x06 \x01(\tR\rconsumerGroup\"\x86\x01\n" +
	"\x15GeneratorSourceConfig\x12*\n" +
	"\x06schema\x18\x01 \x01(\v2\x12.isotope.v1.SchemaR\x06schema\x12&\n" +
	"\x0frows_per_second\x18\x02 \x01(\x03R\rrowsPerSecond\x12\x19\n" +
	"\bmax_rows\x18\x03 \x01(\x03R\amaxRows\"\x83\x01\n" +
	"\x0fKafkaSinkConfig\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12+\n" +
	"\x11bootstrap_servers\x18\x02 \x01(\tR\x10bootstrapServers\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x15\n" +
	"\x06key_by\x18\x04 \x03(\tR\x05keyBy\".\n" +
	"\x11ConsoleSinkConfig\x12\x19\n" +
	"\bmax_rows\x18\x01 \x01(\x05R\amaxRows\"3\n" +
	"\fFilterConfig\x12#\n" +
	"\rcondition_sql\x18\x01 \x01(\tR\fconditionSql\"\x85\x01\n" +
	"\tMapConfig\x12<\n" +
	"\acolumns\x18\x01 \x03(\v2\".isotope.v1.MapConfig.ColumnsEntryR\acolumns\x1a:\n" +
	"\fColumnsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\rFlatMapConfig\x12#\n" +
	"\runnest_column\x18\x01 \x01(\tR\funnestColumn\x12<\n" +
	"\routput_fields\x18\x02 \x03(\v2\x17.isotope.v1.SchemaFieldR\foutputFields\"\xa8\x01\n" +
	"\x0fAggregateConfig\x12\x19\n" +
	"\bgroup_by\x18\x01 \x03(\tR\agroupBy\x12?\n" +
	"\x06select\x18\x02 \x03(\v2'.isotope.v1.AggregateConfig.SelectEntryR\x06select\x1a9\n" +
	"\vSelectEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\fRenameConfig\x12?\n" +
	"\acolumns\x18\x01 \x03(\v2%.isotope.v1.RenameConfig.ColumnsEntryR\acolumns\x1a:\n" +
	"\fColumnsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\n" +
	"DropConfig\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\"\xa0\x01\n" +
	"\n" +
	"CastConfig\x12=\n" +
	"\acolumns\x18\x01 \x03(\v2#.isotope.v1.CastConfig.ColumnsEntryR\acolumns\x1aS\n" +
	"\fColumnsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.isotope.v1.SchemaFieldR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x0eCoalesceConfig\x12A\n" +
	"\acolumns\x18\x01 \x03(\v2'.isotope.v1.CoalesceConfig.ColumnsEntryR\acolumns\x1a:\n" +
	"\fColumnsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x02\n" +
	"\x0eAddFieldConfig\x12A\n" +
	"\acolumns\x18\x01 \x03(\v2'.isotope.v1.AddFieldConfig.ColumnsEntryR\acolumns\x12;\n" +
	"\x05types\x18\x02 \x03(\v2%.isotope.v1.AddFieldConfig.TypesEntryR\x05types\x1a:\n" +
	"\fColumnsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aQ\n" +
	"\n" +
	"TypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.isotope.v1.SchemaFieldR\x05value:\x028\x01\"\r\n" +
	"\vUnionConfig\"[\n" +
	"\vRouteBranch\x12#\n" +
	"\rcondition_sql\x18\x01 \x01(\tR\fconditionSql\x12'\n" +
	"\x0ftarget_operator\x18\x02 \x01(\tR\x0etargetOperator\"m\n" +
	"\vRouteConfig\x123\n" +
	"\bbranches\x18\x01 \x03(\v2\x17.isotope.v1.RouteBranchR\bbranches\x12)\n" +
	"\x10default_operator\x18\x02 \x01(\tR\x0fdefaultOperator\"O\n" +
	"\x11DeduplicateConfig\x12\x10\n" +
	"\x03key\x18\x01 \x03(\tR\x03key\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\x12\x12\n" +
	"\x04keep\x18\x03 \x01(\tR\x04keep\"\xb9\x01\n" +
	"\n" +
	"TopNConfig\x12!\n" +
	"\fpartition_by\x18\x01 \x03(\tR\vpartitionBy\x12>\n" +
	"\border_by\x18\x02 \x03(\v2#.isotope.v1.TopNConfig.OrderByEntryR\aorderBy\x12\f\n" +
	"\x01n\x18\x03 \x01(\x05R\x01n\x1a:\n" +
	"\fOrderByEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x12TumbleWindowConfig\x12\x12\n" +
	"\x04size\x18\x01 \x01(\tR\x04size\x12\x1f\n" +
	"\vtime_column\x18\x02 \x01(\tR\n" +
	"timeColumn\"^\n" +
	"\x11SlideWindowConfig\x12\x12\n" +
	"\x04size\x18\x01 \x01(\tR\x04size\x12\x14\n" +
	"\x05slide\x18\x02 \x01(\tR\x05slide\x12\x1f\n" +
	"\vtime_column\x18\x03 \x01(\tR\n" +
	"timeColumn\"H\n" +
	"\x13SessionWindowConfig\x12\x10\n" +
	"\x03gap\x18\x01 \x01(\tR\x03gap\x12\x1f\n" +
	"\vtime_column\x18\x02 \x01(\tR\n" +
	"timeColumn\"o\n" +
	"\x0eHashJoinConfig\x12#\n" +
	"\rcondition_sql\x18\x01 \x01(\tR\fconditionSql\x12\x1b\n" +
	"\tjoin_type\x18\x02 \x01(\tR\bjoinType\x12\x1b\n" +
	"\tstate_ttl\x18\x03 \x01(\tR\bstateTtl\"N\n" +
	"\x12TemporalJoinConfig\x12#\n" +
	"\rcondition_sql\x18\x01 \x01(\tR\fconditionSql\x12\x13\n" +
	"\x05as_of\x18\x02 \x01(\tR\x04asOf\"\xc6\x02\n" +
	"\x10LookupJoinConfig\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12#\n" +
	"\rcondition_sql\x18\x03 \x01(\tR\fconditionSql\x12@\n" +
	"\x06select\x18\x04 \x03(\v2(.isotope.v1.LookupJoinConfig.SelectEntryR\x06select\x123\n" +
	"\x05async\x18\x05 \x01(\v2\x1d.isotope.v1.LookupAsyncConfigR\x05async\x123\n" +
	"\x05cache\x18\x06 \x01(\v2\x1d.isotope.v1.LookupCacheConfigR\x05cache\x1a9\n" +
	"\vSelectEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x11LookupAsyncConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\tR\atimeout\"T\n" +
	"\x11LookupCacheConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bmax_rows\x18\x02 \x01(\x03R\amaxRows\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\tR\x03ttl\"\x9c\x01\n" +
	"\x12IntervalJoinConfig\x12#\n" +
	"\rcondition_sql\x18\x01 \x01(\tR\fconditionSql\x12#\n" +
	"\rinterval_from\x18\x02 \x01(\tR\fintervalFrom\x12\x1f\n" +
	"\vinterval_to\x18\x03 \x01(\tR\n" +
	"intervalTo\x12\x1b\n" +
	"\tjoin_type\x18\x04 \x01(\tR\bjoinType\" \n" +
	"\fRawSQLConfig\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\"\x84\x04\n" +
	"\x14MatchRecognizeConfig\x12!\n" +
	"\fpartition_by\x18\x01 \x03(\tR\vpartitionBy\x12H\n" +
	"\border_by\x18\x02 \x03(\v2-.isotope.v1.MatchRecognizeConfig.OrderByEntryR\aorderBy\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12D\n" +
	"\x06define\x18\x04 \x03(\v2,.isotope.v1.MatchRecognizeConfig.DefineEntryR\x06define\x12J\n" +
	"\bmeasures\x18\x05 \x03(\v2..isotope.v1.MatchRecognizeConfig.MeasuresEntryR\bmeasures\x12\x1f\n" +
	"\vafter_match\x18\x06 \x01(\tR\n" +
	"afterMatch\x1a:\n" +
	"\fOrderByEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vDefineEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMeasuresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B?Z=github.com/sandboxws/isotope/runtime/internal/proto/isotopev1b\x06proto3"

var (
	file_isotope_v1_operators_proto_rawDescOnce sync.Once
	file_isotope_v1_operators_proto_rawDescData []byte
)

func file_isotope_v1_operators_proto_rawDescGZIP() []byte {
	file_isotope_v1_operators_proto_rawDescOnce.Do(func() {
		file_isotope_v1_operators_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_isotope_v1_operators_proto_rawDesc), len(file_isotope_v1_operators_proto_rawDesc)))
	})
	return file_isotope_v1_operators_proto_rawDescData
}

var file_isotope_v1_operators_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_isotope_v1_operators_proto_goTypes = []any{
	(*KafkaSourceConfig)(nil),     // 0: isotope.v1.KafkaSourceConfig
	(*GeneratorSourceConfig)(nil), // 1: isotope.v1.GeneratorSourceConfig
	(*KafkaSinkConfig)(nil),       // 2: isotope.v1.KafkaSinkConfig
	(*ConsoleSinkConfig)(nil),     // 3: isotope.v1.ConsoleSinkConfig
	(*FilterConfig)(nil),          // 4: isotope.v1.FilterConfig
	(*MapConfig)(nil),             // 5: isotope.v1.MapConfig
	(*FlatMapConfig)(nil),         // 6: isotope.v1.FlatMapConfig
	(*AggregateConfig)(nil),       // 7: isotope.v1.AggregateConfig
	(*RenameConfig)(nil),          // 8: isotope.v1.RenameConfig
	(*DropConfig)(nil),            // 9: isotope.v1.DropConfig
	(*CastConfig)(nil),            // 10: isotope.v1.CastConfig
	(*CoalesceConfig)(nil),        // 11: isotope.v1.CoalesceConfig
	(*AddFieldConfig)(nil),        // 12: isotope.v1.AddFieldConfig
	(*UnionConfig)(nil),           // 13: isotope.v1.UnionConfig
	(*RouteBranch)(nil),           // 14: isotope.v1.RouteBranch
	(*RouteConfig)(nil),           // 15: isotope.v1.RouteConfig
	(*DeduplicateConfig)(nil),     // 16: isotope.v1.DeduplicateConfig
	(*TopNConfig)(nil),            // 17: isotope.v1.TopNConfig
	(*TumbleWindowConfig)(nil),    // 18: isotope.v1.TumbleWindowConfig
	(*SlideWindowConfig)(nil),     // 19: isotope.v1.SlideWindowConfig
	(*SessionWindowConfig)(nil),   // 20: isotope.v1.SessionWindowConfig
	(*HashJoinConfig)(nil),        // 21: isotope.v1.HashJoinConfig
	(*TemporalJoinConfig)(nil),    // 22: isotope.v1.TemporalJoinConfig
	(*LookupJoinConfig)(nil),      // 23: isotope.v1.LookupJoinConfig
	(*LookupAsyncConfig)(nil),     // 24: isotope.v1.LookupAsyncConfig
	(*LookupCacheConfig)(nil),     // 25: isotope.v1.LookupCacheConfig
	(*IntervalJoinConfig)(nil),    // 26: isotope.v1.IntervalJoinConfig
	(*RawSQLConfig)(nil),          // 27: isotope.v1.RawSQLConfig
	(*MatchRecognizeConfig)(nil),  // 28: isotope.v1.MatchRecognizeConfig
	nil,                           // 29: isotope.v1.MapConfig.ColumnsEntry
	nil,                           // 30: isotope.v1.AggregateConfig.SelectEntry
	nil,                           // 31: isotope.v1.RenameConfig.ColumnsEntry
	nil,                           // 32: isotope.v1.CastConfig.ColumnsEntry
	nil,                           // 33: isotope.v1.CoalesceConfig.ColumnsEntry
	nil,                           // 34: isotope.v1.AddFieldConfig.ColumnsEntry
	nil,                           // 35: isotope.v1.AddFieldConfig.TypesEntry
	nil,                           // 36: isotope.v1.TopNConfig.OrderByEntry
	nil,                           // 37: isotope.v1.LookupJoinConfig.SelectEntry
	nil,                           // 38: isotope.v1.MatchRecognizeConfig.OrderByEntry
	nil,                           // 39: isotope.v1.MatchRecognizeConfig.DefineEntry
	nil,                           // 40: isotope.v1.MatchRecognizeConfig.MeasuresEntry
	(*Schema)(nil),                // 41: isotope.v1.Schema
	(*SchemaField)(nil),           // 42: isotope.v1.SchemaField
}
var file_isotope_v1_operators_proto_depIdxs = []int32{
	41, // 0: isotope.v1.KafkaSourceConfig.schema:type_name -> isotope.v1.Schema
	41, // 1: isotope.v1.GeneratorSourceConfig.schema:type_name -> isotope.v1.Schema
	29, // 2: isotope.v1.MapConfig.columns:type_name -> isotope.v1.MapConfig.ColumnsEntry
	42, // 3: isotope.v1.FlatMapConfig.output_fields:type_name -> isotope.v1.SchemaField
	30, // 4: isotope.v1.AggregateConfig.select:type_name -> isotope.v1.AggregateConfig.SelectEntry
	31, // 5: isotope.v1.RenameConfig.columns:type_name -> isotope.v1.RenameConfig.ColumnsEntry
	32, // 6: isotope.v1.CastConfig.columns:type_name -> isotope.v1.CastConfig.ColumnsEntry
	33, // 7: isotope.v1.CoalesceConfig.columns:type_name -> isotope.v1.CoalesceConfig.ColumnsEntry
	34, // 8: isotope.v1.AddFieldConfig.columns:type_name -> isotope.v1.AddFieldConfig.ColumnsEntry
	35, // 9: isotope.v1.AddFieldConfig.types:type_name -> isotope.v1.AddFieldConfig.TypesEntry
	14, // 10: isotope.v1.RouteConfig.branches:type_name -> isotope.v1.RouteBranch
	36, // 11: isotope.v1.TopNConfig.order_by:type_name -> isotope.v1.TopNConfig.OrderByEntry
	37, // 12: isotope.v1.LookupJoinConfig.select:type_name -> isotope.v1.LookupJoinConfig.SelectEntry
	24, // 13: isotope.v1.LookupJoinConfig.async:type_name -> isotope.v1.LookupAsyncConfig
	25, // 14: isotope.v1.LookupJoinConfig.cache:type_name -> isotope.v1.LookupCacheConfig
	38, // 15: isotope.v1.MatchRecognizeConfig.order_by:type_name -> isotope.v1.MatchRecognizeConfig.OrderByEntry
	39, // 16: isotope.v1.MatchRecognizeConfig.define:type_name -> isotope.v1.MatchRecognizeConfig.DefineEntry
	40, // 17: isotope.v1.MatchRecognizeConfig.measures:type_name -> isotope.v1.MatchRecognizeConfig.MeasuresEntry
	42, // 18: isotope.v1.CastConfig.ColumnsEntry.value:type_name -> isotope.v1.SchemaField
	42, // 19: isotope.v1.AddFieldConfig.TypesEntry.value:type_name -> isotope.v1.SchemaField
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_isotope_v1_operators_proto_init() }
func file_isotope_v1_operators_proto_init() {
	if File_isotope_v1_operators_proto != nil {
		return
	}
	file_isotope_v1_schema_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_isotope_v1_operators_proto_rawDesc), len(file_isotope_v1_operators_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_isotope_v1_operators_proto_goTypes,
		DependencyIndexes: file_isotope_v1_operators_proto_depIdxs,
		MessageInfos:      file_isotope_v1_operators_proto_msgTypes,
	}.Build()
	File_isotope_v1_operators_proto = out.File
	file_isotope_v1_operators_proto_goTypes = nil
	file_isotope_v1_operators_proto_depIdxs = nil
}
