// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: isotope/v1/plan.proto

package isotopev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PipelineMode int32

const (
	PipelineMode_PIPELINE_MODE_UNSPECIFIED PipelineMode = 0
	PipelineMode_PIPELINE_MODE_STREAMING   PipelineMode = 1
	PipelineMode_PIPELINE_MODE_BATCH       PipelineMode = 2
)

// Enum value maps for PipelineMode.
var (
	PipelineMode_name = map[int32]string{
		0: "PIPELINE_MODE_UNSPECIFIED",
		1: "PIPELINE_MODE_STREAMING",
		2: "PIPELINE_MODE_BATCH",
	}
	PipelineMode_value = map[string]int32{
		"PIPELINE_MODE_UNSPECIFIED": 0,
		"PIPELINE_MODE_STREAMING":   1,
		"PIPELINE_MODE_BATCH":       2,
	}
)

func (x PipelineMode) Enum() *PipelineMode {
	p := new(PipelineMode)
	*p = x
	return p
}

func (x PipelineMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineMode) Descriptor() protoreflect.EnumDescriptor {
	return file_isotope_v1_plan_proto_enumTypes[0].Descriptor()
}

func (PipelineMode) Type() protoreflect.EnumType {
	return &file_isotope_v1_plan_proto_enumTypes[0]
}

func (x PipelineMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineMode.Descriptor instead.
func (PipelineMode) EnumDescriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{0}
}

type OperatorType int32

const (
	OperatorType_OPERATOR_TYPE_UNSPECIFIED OperatorType = 0
	// Sources
	OperatorType_OPERATOR_TYPE_KAFKA_SOURCE     OperatorType = 1
	OperatorType_OPERATOR_TYPE_GENERATOR_SOURCE OperatorType = 2
	// Sinks
	OperatorType_OPERATOR_TYPE_KAFKA_SINK   OperatorType = 10
	OperatorType_OPERATOR_TYPE_CONSOLE_SINK OperatorType = 11
	// Stateless transforms
	OperatorType_OPERATOR_TYPE_FILTER    OperatorType = 20
	OperatorType_OPERATOR_TYPE_MAP       OperatorType = 21
	OperatorType_OPERATOR_TYPE_FLAT_MAP  OperatorType = 22
	OperatorType_OPERATOR_TYPE_RENAME    OperatorType = 23
	OperatorType_OPERATOR_TYPE_DROP      OperatorType = 24
	OperatorType_OPERATOR_TYPE_CAST      OperatorType = 25
	OperatorType_OPERATOR_TYPE_UNION     OperatorType = 26
	OperatorType_OPERATOR_TYPE_ROUTE     OperatorType = 27
	OperatorType_OPERATOR_TYPE_COALESCE  OperatorType = 28
	OperatorType_OPERATOR_TYPE_ADD_FIELD OperatorType = 29
	// Stateful transforms
	OperatorType_OPERATOR_TYPE_AGGREGATE   OperatorType = 40
	OperatorType_OPERATOR_TYPE_DEDUPLICATE OperatorType = 41
	OperatorType_OPERATOR_TYPE_TOP_N       OperatorType = 42
	// Windows
	OperatorType_OPERATOR_TYPE_TUMBLE_WINDOW  OperatorType = 50
	OperatorType_OPERATOR_TYPE_SLIDE_WINDOW   OperatorType = 51
	OperatorType_OPERATOR_TYPE_SESSION_WINDOW OperatorType = 52
	// Joins
	OperatorType_OPERATOR_TYPE_HASH_JOIN     OperatorType = 60
	OperatorType_OPERATOR_TYPE_TEMPORAL_JOIN OperatorType = 61
	OperatorType_OPERATOR_TYPE_LOOKUP_JOIN   OperatorType = 62
	OperatorType_OPERATOR_TYPE_INTERVAL_JOIN OperatorType = 63
	// Escape hatches
	OperatorType_OPERATOR_TYPE_RAW_SQL         OperatorType = 70
	OperatorType_OPERATOR_TYPE_MATCH_RECOGNIZE OperatorType = 71
)

// Enum value maps for OperatorType.
var (
	OperatorType_name = map[int32]string{
		0:  "OPERATOR_TYPE_UNSPECIFIED",
		1:  "OPERATOR_TYPE_KAFKA_SOURCE",
		2:  "OPERATOR_TYPE_GENERATOR_SOURCE",
		10: "OPERATOR_TYPE_KAFKA_SINK",
		11: "OPERATOR_TYPE_CONSOLE_SINK",
		20: "OPERATOR_TYPE_FILTER",
		21: "OPERATOR_TYPE_MAP",
		22: "OPERATOR_TYPE_FLAT_MAP",
		23: "OPERATOR_TYPE_RENAME",
		24: "OPERATOR_TYPE_DROP",
		25: "OPERATOR_TYPE_CAST",
		26: "OPERATOR_TYPE_UNION",
		27: "OPERATOR_TYPE_ROUTE",
		28: "OPERATOR_TYPE_COALESCE",
		29: "OPERATOR_TYPE_ADD_FIELD",
		40: "OPERATOR_TYPE_AGGREGATE",
		41: "OPERATOR_TYPE_DEDUPLICATE",
		42: "OPERATOR_TYPE_TOP_N",
		50: "OPERATOR_TYPE_TUMBLE_WINDOW",
		51: "OPERATOR_TYPE_SLIDE_WINDOW",
		52: "OPERATOR_TYPE_SESSION_WINDOW",
		60: "OPERATOR_TYPE_HASH_JOIN",
		61: "OPERATOR_TYPE_TEMPORAL_JOIN",
		62: "OPERATOR_TYPE_LOOKUP_JOIN",
		63: "OPERATOR_TYPE_INTERVAL_JOIN",
		70: "OPERATOR_TYPE_RAW_SQL",
		71: "OPERATOR_TYPE_MATCH_RECOGNIZE",
	}
	OperatorType_value = map[string]int32{
		"OPERATOR_TYPE_UNSPECIFIED":      0,
		"OPERATOR_TYPE_KAFKA_SOURCE":     1,
		"OPERATOR_TYPE_GENERATOR_SOURCE": 2,
		"OPERATOR_TYPE_KAFKA_SINK":       10,
		"OPERATOR_TYPE_CONSOLE_SINK":     11,
		"OPERATOR_TYPE_FILTER":           20,
		"OPERATOR_TYPE_MAP":              21,
		"OPERATOR_TYPE_FLAT_MAP":         22,
		"OPERATOR_TYPE_RENAME":           23,
		"OPERATOR_TYPE_DROP":             24,
		"OPERATOR_TYPE_CAST":             25,
		"OPERATOR_TYPE_UNION":            26,
		"OPERATOR_TYPE_ROUTE":            27,
		"OPERATOR_TYPE_COALESCE":         28,
		"OPERATOR_TYPE_ADD_FIELD":        29,
		"OPERATOR_TYPE_AGGREGATE":        40,
		"OPERATOR_TYPE_DEDUPLICATE":      41,
		"OPERATOR_TYPE_TOP_N":            42,
		"OPERATOR_TYPE_TUMBLE_WINDOW":    50,
		"OPERATOR_TYPE_SLIDE_WINDOW":     51,
		"OPERATOR_TYPE_SESSION_WINDOW":   52,
		"OPERATOR_TYPE_HASH_JOIN":        60,
		"OPERATOR_TYPE_TEMPORAL_JOIN":    61,
		"OPERATOR_TYPE_LOOKUP_JOIN":      62,
		"OPERATOR_TYPE_INTERVAL_JOIN":    63,
		"OPERATOR_TYPE_RAW_SQL":          70,
		"OPERATOR_TYPE_MATCH_RECOGNIZE":  71,
	}
)

func (x OperatorType) Enum() *OperatorType {
	p := new(OperatorType)
	*p = x
	return p
}

func (x OperatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_isotope_v1_plan_proto_enumTypes[1].Descriptor()
}

func (OperatorType) Type() protoreflect.EnumType {
	return &file_isotope_v1_plan_proto_enumTypes[1]
}

func (x OperatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatorType.Descriptor instead.
func (OperatorType) EnumDescriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{1}
}

type ExecutionStrategy int32

const (
	ExecutionStrategy_EXECUTION_STRATEGY_UNSPECIFIED        ExecutionStrategy = 0
	ExecutionStrategy_EXECUTION_STRATEGY_ARROW_NATIVE       ExecutionStrategy = 1
	ExecutionStrategy_EXECUTION_STRATEGY_DUCKDB_MICRO_BATCH ExecutionStrategy = 2
)

// Enum value maps for ExecutionStrategy.
var (
	ExecutionStrategy_name = map[int32]string{
		0: "EXECUTION_STRATEGY_UNSPECIFIED",
		1: "EXECUTION_STRATEGY_ARROW_NATIVE",
		2: "EXECUTION_STRATEGY_DUCKDB_MICRO_BATCH",
	}
	ExecutionStrategy_value = map[string]int32{
		"EXECUTION_STRATEGY_UNSPECIFIED":        0,
		"EXECUTION_STRATEGY_ARROW_NATIVE":       1,
		"EXECUTION_STRATEGY_DUCKDB_MICRO_BATCH": 2,
	}
)

func (x ExecutionStrategy) Enum() *ExecutionStrategy {
	p := new(ExecutionStrategy)
	*p = x
	return p
}

func (x ExecutionStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_isotope_v1_plan_proto_enumTypes[2].Descriptor()
}

func (ExecutionStrategy) Type() protoreflect.EnumType {
	return &file_isotope_v1_plan_proto_enumTypes[2]
}

func (x ExecutionStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStrategy.Descriptor instead.
func (ExecutionStrategy) EnumDescriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{2}
}

type ChangelogMode int32

const (
	ChangelogMode_CHANGELOG_MODE_UNSPECIFIED ChangelogMode = 0
	ChangelogMode_CHANGELOG_MODE_APPEND_ONLY ChangelogMode = 1
	ChangelogMode_CHANGELOG_MODE_RETRACT     ChangelogMode = 2
	ChangelogMode_CHANGELOG_MODE_UPSERT      ChangelogMode = 3
)

// Enum value maps for ChangelogMode.
var (
	ChangelogMode_name = map[int32]string{
		0: "CHANGELOG_MODE_UNSPECIFIED",
		1: "CHANGELOG_MODE_APPEND_ONLY",
		2: "CHANGELOG_MODE_RETRACT",
		3: "CHANGELOG_MODE_UPSERT",
	}
	ChangelogMode_value = map[string]int32{
		"CHANGELOG_MODE_UNSPECIFIED": 0,
		"CHANGELOG_MODE_APPEND_ONLY": 1,
		"CHANGELOG_MODE_RETRACT":     2,
		"CHANGELOG_MODE_UPSERT":      3,
	}
)

func (x ChangelogMode) Enum() *ChangelogMode {
	p := new(ChangelogMode)
	*p = x
	return p
}

func (x ChangelogMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangelogMode) Descriptor() protoreflect.EnumDescriptor {
	return file_isotope_v1_plan_proto_enumTypes[3].Descriptor()
}

func (ChangelogMode) Type() protoreflect.EnumType {
	return &file_isotope_v1_plan_proto_enumTypes[3]
}

func (x ChangelogMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangelogMode.Descriptor instead.
func (ChangelogMode) EnumDescriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{3}
}

type ShuffleStrategy int32

const (
	ShuffleStrategy_SHUFFLE_STRATEGY_UNSPECIFIED ShuffleStrategy = 0
	ShuffleStrategy_SHUFFLE_STRATEGY_FORWARD     ShuffleStrategy = 1
	ShuffleStrategy_SHUFFLE_STRATEGY_HASH        ShuffleStrategy = 2
	ShuffleStrategy_SHUFFLE_STRATEGY_BROADCAST   ShuffleStrategy = 3
	ShuffleStrategy_SHUFFLE_STRATEGY_ROUND_ROBIN ShuffleStrategy = 4
	ShuffleStrategy_SHUFFLE_STRATEGY_RANGE       ShuffleStrategy = 5
)

// Enum value maps for ShuffleStrategy.
var (
	ShuffleStrategy_name = map[int32]string{
		0: "SHUFFLE_STRATEGY_UNSPECIFIED",
		1: "SHUFFLE_STRATEGY_FORWARD",
		2: "SHUFFLE_STRATEGY_HASH",
		3: "SHUFFLE_STRATEGY_BROADCAST",
		4: "SHUFFLE_STRATEGY_ROUND_ROBIN",
		5: "SHUFFLE_STRATEGY_RANGE",
	}
	ShuffleStrategy_value = map[string]int32{
		"SHUFFLE_STRATEGY_UNSPECIFIED": 0,
		"SHUFFLE_STRATEGY_FORWARD":     1,
		"SHUFFLE_STRATEGY_HASH":        2,
		"SHUFFLE_STRATEGY_BROADCAST":   3,
		"SHUFFLE_STRATEGY_ROUND_ROBIN": 4,
		"SHUFFLE_STRATEGY_RANGE":       5,
	}
)

func (x ShuffleStrategy) Enum() *ShuffleStrategy {
	p := new(ShuffleStrategy)
	*p = x
	return p
}

func (x ShuffleStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShuffleStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_isotope_v1_plan_proto_enumTypes[4].Descriptor()
}

func (ShuffleStrategy) Type() protoreflect.EnumType {
	return &file_isotope_v1_plan_proto_enumTypes[4]
}

func (x ShuffleStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShuffleStrategy.Descriptor instead.
func (ShuffleStrategy) EnumDescriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{4}
}

type ExecutionPlan struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PipelineName       string                 `protobuf:"bytes,1,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"`
	DefaultParallelism int32                  `protobuf:"varint,2,opt,name=default_parallelism,json=defaultParallelism,proto3" json:"default_parallelism,omitempty"`
	Mode               PipelineMode           `protobuf:"varint,3,opt,name=mode,proto3,enum=isotope.v1.PipelineMode" json:"mode,omitempty"`
	Checkpoint         *CheckpointConfig      `protobuf:"bytes,4,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	State              *StateConfig           `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Restart            *RestartConfig         `protobuf:"bytes,6,opt,name=restart,proto3" json:"restart,omitempty"`
	Operators          []*OperatorNode        `protobuf:"bytes,7,rep,name=operators,proto3" json:"operators,omitempty"`
	Edges              []*Edge                `protobuf:"bytes,8,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecutionPlan) Reset() {
	*x = ExecutionPlan{}
	mi := &file_isotope_v1_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPlan) ProtoMessage() {}

func (x *ExecutionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPlan.ProtoReflect.Descriptor instead.
func (*ExecutionPlan) Descriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionPlan) GetPipelineName() string {
	if x != nil {
		return x.PipelineName
	}
	return ""
}

func (x *ExecutionPlan) GetDefaultParallelism() int32 {
	if x != nil {
		return x.DefaultParallelism
	}
	return 0
}

func (x *ExecutionPlan) GetMode() PipelineMode {
	if x != nil {
		return x.Mode
	}
	return PipelineMode_PIPELINE_MODE_UNSPECIFIED
}

func (x *ExecutionPlan) GetCheckpoint() *CheckpointConfig {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *ExecutionPlan) GetState() *StateConfig {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ExecutionPlan) GetRestart() *RestartConfig {
	if x != nil {
		return x.Restart
	}
	return nil
}

func (x *ExecutionPlan) GetOperators() []*OperatorNode {
	if x != nil {
		return x.Operators
	}
	return nil
}

func (x *ExecutionPlan) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type CheckpointConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      string                 `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // "exactly-once" | "at-least-once"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointConfig) Reset() {
	*x = CheckpointConfig{}
	mi := &file_isotope_v1_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointConfig) ProtoMessage() {}

func (x *CheckpointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointConfig.ProtoReflect.Descriptor instead.
func (*CheckpointConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{1}
}

func (x *CheckpointConfig) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *CheckpointConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type StateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backend       string                 `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"` // "pebble" | "memory"
	Ttl           string                 `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateConfig) Reset() {
	*x = StateConfig{}
	mi := &file_isotope_v1_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateConfig) ProtoMessage() {}

func (x *StateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateConfig.ProtoReflect.Descriptor instead.
func (*StateConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{2}
}

func (x *StateConfig) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *StateConfig) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

type RestartConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "fixed-delay" | "failure-rate" | "no-restart"
	Attempts      int32                  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Delay         string                 `protobuf:"bytes,3,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartConfig) Reset() {
	*x = RestartConfig{}
	mi := &file_isotope_v1_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartConfig) ProtoMessage() {}

func (x *RestartConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartConfig.ProtoReflect.Descriptor instead.
func (*RestartConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{3}
}

func (x *RestartConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RestartConfig) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *RestartConfig) GetDelay() string {
	if x != nil {
		return x.Delay
	}
	return ""
}

type SourceLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceLocation) Reset() {
	*x = SourceLocation{}
	mi := &file_isotope_v1_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceLocation) ProtoMessage() {}

func (x *SourceLocation) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceLocation.ProtoReflect.Descriptor instead.
func (*SourceLocation) Descriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{4}
}

func (x *SourceLocation) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *SourceLocation) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *SourceLocation) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type OperatorNode struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorType      OperatorType           `protobuf:"varint,2,opt,name=operator_type,json=operatorType,proto3,enum=isotope.v1.OperatorType" json:"operator_type,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Parallelism       int32                  `protobuf:"varint,4,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	InputSchema       *Schema                `protobuf:"bytes,5,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema      *Schema                `protobuf:"bytes,6,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	ChangelogMode     ChangelogMode          `protobuf:"varint,7,opt,name=changelog_mode,json=changelogMode,proto3,enum=isotope.v1.ChangelogMode" json:"changelog_mode,omitempty"`
	SourceLocation    *SourceLocation        `protobuf:"bytes,8,opt,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	ExecutionStrategy ExecutionStrategy      `protobuf:"varint,9,opt,name=execution_strategy,json=executionStrategy,proto3,enum=isotope.v1.ExecutionStrategy" json:"execution_strategy,omitempty"`
	// Operator-specific configuration — exactly one must be set.
	//
	// Types that are valid to be assigned to Config:
	//
	//	*OperatorNode_KafkaSource
	//	*OperatorNode_GeneratorSource
	//	*OperatorNode_KafkaSink
	//	*OperatorNode_ConsoleSink
	//	*OperatorNode_Filter
	//	*OperatorNode_Map
	//	*OperatorNode_FlatMap
	//	*OperatorNode_Rename
	//	*OperatorNode_Drop
	//	*OperatorNode_Cast
	//	*OperatorNode_Union
	//	*OperatorNode_Route
	//	*OperatorNode_Coalesce
	//	*OperatorNode_AddField
	//	*OperatorNode_Aggregate
	//	*OperatorNode_Deduplicate
	//	*OperatorNode_TopN
	//	*OperatorNode_TumbleWindow
	//	*OperatorNode_SlideWindow
	//	*OperatorNode_SessionWindow
	//	*OperatorNode_HashJoin
	//	*OperatorNode_TemporalJoin
	//	*OperatorNode_LookupJoin
	//	*OperatorNode_IntervalJoin
	//	*OperatorNode_RawSql
	//	*OperatorNode_MatchRecognize
	Config        isOperatorNode_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorNode) Reset() {
	*x = OperatorNode{}
	mi := &file_isotope_v1_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorNode) ProtoMessage() {}

func (x *OperatorNode) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorNode.ProtoReflect.Descriptor instead.
func (*OperatorNode) Descriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{5}
}

func (x *OperatorNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OperatorNode) GetOperatorType() OperatorType {
	if x != nil {
		return x.OperatorType
	}
	return OperatorType_OPERATOR_TYPE_UNSPECIFIED
}

func (x *OperatorNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperatorNode) GetParallelism() int32 {
	if x != nil {
		return x.Parallelism
	}
	return 0
}

func (x *OperatorNode) GetInputSchema() *Schema {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *OperatorNode) GetOutputSchema() *Schema {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

func (x *OperatorNode) GetChangelogMode() ChangelogMode {
	if x != nil {
		return x.ChangelogMode
	}
	return ChangelogMode_CHANGELOG_MODE_UNSPECIFIED
}

func (x *OperatorNode) GetSourceLocation() *SourceLocation {
	if x != nil {
		return x.SourceLocation
	}
	return nil
}

func (x *OperatorNode) GetExecutionStrategy() ExecutionStrategy {
	if x != nil {
		return x.ExecutionStrategy
	}
	return ExecutionStrategy_EXECUTION_STRATEGY_UNSPECIFIED
}

func (x *OperatorNode) GetConfig() isOperatorNode_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *OperatorNode) GetKafkaSource() *KafkaSourceConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_KafkaSource); ok {
			return x.KafkaSource
		}
	}
	return nil
}

func (x *OperatorNode) GetGeneratorSource() *GeneratorSourceConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_GeneratorSource); ok {
			return x.GeneratorSource
		}
	}
	return nil
}

func (x *OperatorNode) GetKafkaSink() *KafkaSinkConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_KafkaSink); ok {
			return x.KafkaSink
		}
	}
	return nil
}

func (x *OperatorNode) GetConsoleSink() *ConsoleSinkConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_ConsoleSink); ok {
			return x.ConsoleSink
		}
	}
	return nil
}

func (x *OperatorNode) GetFilter() *FilterConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_Filter); ok {
			return x.Filter
		}
	}
	return nil
}

func (x *OperatorNode) GetMap() *MapConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_Map); ok {
			return x.Map
		}
	}
	return nil
}

func (x *OperatorNode) GetFlatMap() *FlatMapConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_FlatMap); ok {
			return x.FlatMap
		}
	}
	return nil
}

func (x *OperatorNode) GetRename() *RenameConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_Rename); ok {
			return x.Rename
		}
	}
	return nil
}

func (x *OperatorNode) GetDrop() *DropConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_Drop); ok {
			return x.Drop
		}
	}
	return nil
}

func (x *OperatorNode) GetCast() *CastConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_Cast); ok {
			return x.Cast
		}
	}
	return nil
}

func (x *OperatorNode) GetUnion() *UnionConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_Union); ok {
			return x.Union
		}
	}
	return nil
}

func (x *OperatorNode) GetRoute() *RouteConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_Route); ok {
			return x.Route
		}
	}
	return nil
}

func (x *OperatorNode) GetCoalesce() *CoalesceConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_Coalesce); ok {
			return x.Coalesce
		}
	}
	return nil
}

func (x *OperatorNode) GetAddField() *AddFieldConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_AddField); ok {
			return x.AddField
		}
	}
	return nil
}

func (x *OperatorNode) GetAggregate() *AggregateConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_Aggregate); ok {
			return x.Aggregate
		}
	}
	return nil
}

func (x *OperatorNode) GetDeduplicate() *DeduplicateConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_Deduplicate); ok {
			return x.Deduplicate
		}
	}
	return nil
}

func (x *OperatorNode) GetTopN() *TopNConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_TopN); ok {
			return x.TopN
		}
	}
	return nil
}

func (x *OperatorNode) GetTumbleWindow() *TumbleWindowConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_TumbleWindow); ok {
			return x.TumbleWindow
		}
	}
	return nil
}

func (x *OperatorNode) GetSlideWindow() *SlideWindowConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_SlideWindow); ok {
			return x.SlideWindow
		}
	}
	return nil
}

func (x *OperatorNode) GetSessionWindow() *SessionWindowConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_SessionWindow); ok {
			return x.SessionWindow
		}
	}
	return nil
}

func (x *OperatorNode) GetHashJoin() *HashJoinConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_HashJoin); ok {
			return x.HashJoin
		}
	}
	return nil
}

func (x *OperatorNode) GetTemporalJoin() *TemporalJoinConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_TemporalJoin); ok {
			return x.TemporalJoin
		}
	}
	return nil
}

func (x *OperatorNode) GetLookupJoin() *LookupJoinConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_LookupJoin); ok {
			return x.LookupJoin
		}
	}
	return nil
}

func (x *OperatorNode) GetIntervalJoin() *IntervalJoinConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_IntervalJoin); ok {
			return x.IntervalJoin
		}
	}
	return nil
}

func (x *OperatorNode) GetRawSql() *RawSQLConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_RawSql); ok {
			return x.RawSql
		}
	}
	return nil
}

func (x *OperatorNode) GetMatchRecognize() *MatchRecognizeConfig {
	if x != nil {
		if x, ok := x.Config.(*OperatorNode_MatchRecognize); ok {
			return x.MatchRecognize
		}
	}
	return nil
}

type isOperatorNode_Config interface {
	isOperatorNode_Config()
}

type OperatorNode_KafkaSource struct {
	// Sources
	KafkaSource *KafkaSourceConfig `protobuf:"bytes,100,opt,name=kafka_source,json=kafkaSource,proto3,oneof"`
}

type OperatorNode_GeneratorSource struct {
	GeneratorSource *GeneratorSourceConfig `protobuf:"bytes,101,opt,name=generator_source,json=generatorSource,proto3,oneof"`
}

type OperatorNode_KafkaSink struct {
	// Sinks
	KafkaSink *KafkaSinkConfig `protobuf:"bytes,110,opt,name=kafka_sink,json=kafkaSink,proto3,oneof"`
}

type OperatorNode_ConsoleSink struct {
	ConsoleSink *ConsoleSinkConfig `protobuf:"bytes,111,opt,name=console_sink,json=consoleSink,proto3,oneof"`
}

type OperatorNode_Filter struct {
	// Stateless transforms
	Filter *FilterConfig `protobuf:"bytes,120,opt,name=filter,proto3,oneof"`
}

type OperatorNode_Map struct {
	Map *MapConfig `protobuf:"bytes,121,opt,name=map,proto3,oneof"`
}

type OperatorNode_FlatMap struct {
	FlatMap *FlatMapConfig `protobuf:"bytes,122,opt,name=flat_map,json=flatMap,proto3,oneof"`
}

type OperatorNode_Rename struct {
	Rename *RenameConfig `protobuf:"bytes,123,opt,name=rename,proto3,oneof"`
}

type OperatorNode_Drop struct {
	Drop *DropConfig `protobuf:"bytes,124,opt,name=drop,proto3,oneof"`
}

type OperatorNode_Cast struct {
	Cast *CastConfig `protobuf:"bytes,125,opt,name=cast,proto3,oneof"`
}

type OperatorNode_Union struct {
	Union *UnionConfig `protobuf:"bytes,126,opt,name=union,proto3,oneof"`
}

type OperatorNode_Route struct {
	Route *RouteConfig `protobuf:"bytes,127,opt,name=route,proto3,oneof"`
}

type OperatorNode_Coalesce struct {
	Coalesce *CoalesceConfig `protobuf:"bytes,128,opt,name=coalesce,proto3,oneof"`
}

type OperatorNode_AddField struct {
	AddField *AddFieldConfig `protobuf:"bytes,129,opt,name=add_field,json=addField,proto3,oneof"`
}

type OperatorNode_Aggregate struct {
	// Stateful transforms
	Aggregate *AggregateConfig `protobuf:"bytes,140,opt,name=aggregate,proto3,oneof"`
}

type OperatorNode_Deduplicate struct {
	Deduplicate *DeduplicateConfig `protobuf:"bytes,141,opt,name=deduplicate,proto3,oneof"`
}

type OperatorNode_TopN struct {
	TopN *TopNConfig `protobuf:"bytes,142,opt,name=top_n,json=topN,proto3,oneof"`
}

type OperatorNode_TumbleWindow struct {
	// Windows
	TumbleWindow *TumbleWindowConfig `protobuf:"bytes,150,opt,name=tumble_window,json=tumbleWindow,proto3,oneof"`
}

type OperatorNode_SlideWindow struct {
	SlideWindow *SlideWindowConfig `protobuf:"bytes,151,opt,name=slide_window,json=slideWindow,proto3,oneof"`
}

type OperatorNode_SessionWindow struct {
	SessionWindow *SessionWindowConfig `protobuf:"bytes,152,opt,name=session_window,json=sessionWindow,proto3,oneof"`
}

type OperatorNode_HashJoin struct {
	// Joins
	HashJoin *HashJoinConfig `protobuf:"bytes,160,opt,name=hash_join,json=hashJoin,proto3,oneof"`
}

type OperatorNode_TemporalJoin struct {
	TemporalJoin *TemporalJoinConfig `protobuf:"bytes,161,opt,name=temporal_join,json=temporalJoin,proto3,oneof"`
}

type OperatorNode_LookupJoin struct {
	LookupJoin *LookupJoinConfig `protobuf:"bytes,162,opt,name=lookup_join,json=lookupJoin,proto3,oneof"`
}

type OperatorNode_IntervalJoin struct {
	IntervalJoin *IntervalJoinConfig `protobuf:"bytes,163,opt,name=interval_join,json=intervalJoin,proto3,oneof"`
}

type OperatorNode_RawSql struct {
	// Escape hatches
	RawSql *RawSQLConfig `protobuf:"bytes,170,opt,name=raw_sql,json=rawSql,proto3,oneof"`
}

type OperatorNode_MatchRecognize struct {
	MatchRecognize *MatchRecognizeConfig `protobuf:"bytes,171,opt,name=match_recognize,json=matchRecognize,proto3,oneof"`
}

func (*OperatorNode_KafkaSource) isOperatorNode_Config() {}

func (*OperatorNode_GeneratorSource) isOperatorNode_Config() {}

func (*OperatorNode_KafkaSink) isOperatorNode_Config() {}

func (*OperatorNode_ConsoleSink) isOperatorNode_Config() {}

func (*OperatorNode_Filter) isOperatorNode_Config() {}

func (*OperatorNode_Map) isOperatorNode_Config() {}

func (*OperatorNode_FlatMap) isOperatorNode_Config() {}

func (*OperatorNode_Rename) isOperatorNode_Config() {}

func (*OperatorNode_Drop) isOperatorNode_Config() {}

func (*OperatorNode_Cast) isOperatorNode_Config() {}

func (*OperatorNode_Union) isOperatorNode_Config() {}

func (*OperatorNode_Route) isOperatorNode_Config() {}

func (*OperatorNode_Coalesce) isOperatorNode_Config() {}

func (*OperatorNode_AddField) isOperatorNode_Config() {}

func (*OperatorNode_Aggregate) isOperatorNode_Config() {}

func (*OperatorNode_Deduplicate) isOperatorNode_Config() {}

func (*OperatorNode_TopN) isOperatorNode_Config() {}

func (*OperatorNode_TumbleWindow) isOperatorNode_Config() {}

func (*OperatorNode_SlideWindow) isOperatorNode_Config() {}

func (*OperatorNode_SessionWindow) isOperatorNode_Config() {}

func (*OperatorNode_HashJoin) isOperatorNode_Config() {}

func (*OperatorNode_TemporalJoin) isOperatorNode_Config() {}

func (*OperatorNode_LookupJoin) isOperatorNode_Config() {}

func (*OperatorNode_IntervalJoin) isOperatorNode_Config() {}

func (*OperatorNode_RawSql) isOperatorNode_Config() {}

func (*OperatorNode_MatchRecognize) isOperatorNode_Config() {}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromOperator  string                 `protobuf:"bytes,1,opt,name=from_operator,json=fromOperator,proto3" json:"from_operator,omitempty"`
	ToOperator    string                 `protobuf:"bytes,2,opt,name=to_operator,json=toOperator,proto3" json:"to_operator,omitempty"`
	Shuffle       ShuffleStrategy        `protobuf:"varint,3,opt,name=shuffle,proto3,enum=isotope.v1.ShuffleStrategy" json:"shuffle,omitempty"`
	PartitionKeys []string               `protobuf:"bytes,4,rep,name=partition_keys,json=partitionKeys,proto3" json:"partition_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_isotope_v1_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_isotope_v1_plan_proto_rawDescGZIP(), []int{6}
}

func (x *Edge) GetFromOperator() string {
	if x != nil {
		return x.FromOperator
	}
	return ""
}

func (x *Edge) GetToOperator() string {
	if x != nil {
		return x.ToOperator
	}
	return ""
}

func (x *Edge) GetShuffle() ShuffleStrategy {
	if x != nil {
		return x.Shuffle
	}
	return ShuffleStrategy_SHUFFLE_STRATEGY_UNSPECIFIED
}

func (x *Edge) GetPartitionKeys() []string {
	if x != nil {
		return x.PartitionKeys
	}
	return nil
}

var File_isotope_v1_plan_proto protoreflect.FileDescriptor

const file_isotope_v1_plan_proto_rawDesc = "" +
	"\n" +
	"\x15isotope/v1/plan.proto\x12\n" +
	"isotope.v1\x1a\x17isotope/v1/schema.proto\x1a\x1aisotope/v1/operators.proto\"\x95\x03\n" +
	"\rExecutionPlan\x12#\n" +
	"\rpipeline_name\x18\x01 \x01(\tR\fpipelineName\x12/\n" +
	"\x13default_parallelism\x18\x02 \x01(\x05R\x12defaultParallelism\x12,\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x18.isotope.v1.PipelineModeR\x04mode\x12<\n" +
	"\n" +
	"checkpoint\x18\x04 \x01(\v2\x1c.isotope.v1.CheckpointConfigR\n" +
	"checkpoint\x12-\n" +
	"\x05state\x18\x05 \x01(\v2\x17.isotope.v1.StateConfigR\x05state\x123\n" +
	"\arestart\x18\x06 \x01(\v2\x19.isotope.v1.RestartConfigR\arestart\x126\n" +
	"\toperators\x18\a \x03(\v2\x18.isotope.v1.OperatorNodeR\toperators\x12&\n" +
	"\x05edges\x18\b \x03(\v2\x10.isotope.v1.EdgeR\x05edges\"B\n" +
	"\x10CheckpointConfig\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\tR\binterval\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"9\n" +
	"\vStateConfig\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\tR\x03ttl\"U\n" +
	"\rRestartConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\battempts\x18\x02 \x01(\x05R\battempts\x12\x14\n" +
	"\x05delay\x18\x03 \x01(\tR\x05delay\"P\n" +
	"\x0eSourceLocation\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x05R\x06column\"\x94\x10\n" +
	"\fOperatorNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\roperator_type\x18\x02 \x01(\x0e2\x18.isotope.v1.OperatorTypeR\foperatorType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vparallelism\x18\x04 \x01(\x05R\vparallelism\x125\n" +
	"\finput_schema\x18\x05 \x01(\v2\x12.isotope.v1.SchemaR\vinputSchema\x127\n" +
	"\routput_schema\x18\x06 \x01(\v2\x12.isotope.v1.SchemaR\foutputSchema\x12@\n" +
	"\x0echangelog_mode\x18\a \x01(\x0e2\x19.isotope.v1.ChangelogModeR\rchangelogMode\x12C\n" +
	"\x0fsource_location\x18\b \x01(\v2\x1a.isotope.v1.SourceLocationR\x0esourceLocation\x12L\n" +
	"\x12execution_strategy\x18\t \x01(\x0e2\x1d.isotope.v1.ExecutionStrategyR\x11executionStrategy\x12B\n" +
	"\fkafka_source\x18d \x01(\v2\x1d.isotope.v1.KafkaSourceConfigH\x00R\vkafkaSource\x12N\n" +
	"\x10generator_source\x18e \x01(\v2!.isotope.v1.GeneratorSourceConfigH\x00R\x0fgeneratorSource\x12<\n" +
	"\n" +
	"kafka_sink\x18n \x01(\v2\x1b.isotope.v1.KafkaSinkConfigH\x00R\tkafkaSink\x12B\n" +
	"\fconsole_sink\x18o \x01(\v2\x1d.isotope.v1.ConsoleSinkConfigH\x00R\vconsoleSink\x122\n" +
	"\x06filter\x18x \x01(\v2\x18.isotope.v1.FilterConfigH\x00R\x06filter\x12)\n" +
	"\x03map\x18y \x01(\v2\x15.isotope.v1.MapConfigH\x00R\x03map\x126\n" +
	"\bflat_map\x18z \x01(\v2\x19.isotope.v1.FlatMapConfigH\x00R\aflatMap\x122\n" +
	"\x06rename\x18{ \x01(\v2\x18.isotope.v1.RenameConfigH\x00R\x06rename\x12,\n" +
	"\x04drop\x18| \x01(\v2\x16.isotope.v1.DropConfigH\x00R\x04drop\x12,\n" +
	"\x04cast\x18} \x01(\v2\x16.isotope.v1.CastConfigH\x00R\x04cast\x12/\n" +
	"\x05union\x18~ \x01(\v2\x17.isotope.v1.UnionConfigH\x00R\x05union\x12/\n" +
	"\x05route\x18\x7f \x01(\v2\x17.isotope.v1.RouteConfigH\x00R\x05route\x129\n" +
	"\bcoalesce\x18\x80\x01 \x01(\v2\x1a.isotope.v1.CoalesceConfigH\x00R\bcoalesce\x12:\n" +
	"\tadd_field\x18\x81\x01 \x01(\v2\x1a.isotope.v1.AddFieldConfigH\x00R\baddField\x12<\n" +
	"\taggregate\x18\x8c\x01 \x01(\v2\x1b.isotope.v1.AggregateConfigH\x00R\taggregate\x12B\n" +
	"\vdeduplicate\x18\x8d\x01 \x01(\v2\x1d.isotope.v1.DeduplicateConfigH\x00R\vdeduplicate\x12.\n" +
	"\x05top_n\x18\x8e\x01 \x01(\v2\x16.isotope.v1.TopNConfigH\x00R\x04topN\x12F\n" +
	"\rtumble_window\x18\x96\x01 \x01(\v2\x1e.isotope.v1.TumbleWindowConfigH\x00R\ftumbleWindow\x12C\n" +
	"\fslide_window\x18\x97\x01 \x01(\v2\x1d.isotope.v1.SlideWindowConfigH\x00R\vslideWindow\x12I\n" +
	"\x0esession_window\x18\x98\x01 \x01(\v2\x1f.isotope.v1.SessionWindowConfigH\x00R\rsessionWindow\x12:\n" +
	"\thash_join\x18\xa0\x01 \x01(\v2\x1a.isotope.v1.HashJoinConfigH\x00R\bhashJoin\x12F\n" +
	"\rtemporal_join\x18\xa1\x01 \x01(\v2\x1e.isotope.v1.TemporalJoinConfigH\x00R\ftemporalJoin\x12@\n" +
	"\vlookup_join\x18\xa2\x01 \x01(\v2\x1c.isotope.v1.LookupJoinConfigH\x00R\n" +
	"lookupJoin\x12F\n" +
	"\rinterval_join\x18\xa3\x01 \x01(\v2\x1e.isotope.v1.IntervalJoinConfigH\x00R\fintervalJoin\x124\n" +
	"\araw_sql\x18\xaa\x01 \x01(\v2\x18.isotope.v1.RawSQLConfigH\x00R\x06rawSql\x12L\n" +
	"\x0fmatch_recognize\x18\xab\x01 \x01(\v2 .isotope.v1.MatchRecognizeConfigH\x00R\x0ematchRecognizeB\b\n" +
	"\x06config\"\xaa\x01\n" +
	"\x04Edge\x12#\n" +
	"\rfrom_operator\x18\x01 \x01(\tR\ffromOperator\x12\x1f\n" +
	"\vto_operator\x18\x02 \x01(\tR\n" +
	"toOperator\x125\n" +
	"\ashuffle\x18\x03 \x01(\x0e2\x1b.isotope.v1.ShuffleStrategyR\ashuffle\x12%\n" +
	"\x0epartition_keys\x18\x04 \x03(\tR\rpartitionKeys*c\n" +
	"\fPipelineMode\x12\x1d\n" +
	"\x19PIPELINE_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PIPELINE_MODE_STREAMING\x10\x01\x12\x17\n" +
	"\x13PIPELINE_MODE_BATCH\x10\x02*\xa5\x06\n" +
	"\fOperatorType\x12\x1d\n" +
	"\x19OPERATOR_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aOPERATOR_TYPE_KAFKA_SOURCE\x10\x01\x12\"\n" +
	"\x1eOPERATOR_TYPE_GENERATOR_SOURCE\x10\x02\x12\x1c\n" +
	"\x18OPERATOR_TYPE_KAFKA_SINK\x10\n" +
	"\x12\x1e\n" +
	"\x1aOPERATOR_TYPE_CONSOLE_SINK\x10\v\x12\x18\n" +
	"\x14OPERATOR_TYPE_FILTER\x10\x14\x12\x15\n" +
	"\x11OPERATOR_TYPE_MAP\x10\x15\x12\x1a\n" +
	"\x16OPERATOR_TYPE_FLAT_MAP\x10\x16\x12\x18\n" +
	"\x14OPERATOR_TYPE_RENAME\x10\x17\x12\x16\n" +
	"\x12OPERATOR_TYPE_DROP\x10\x18\x12\x16\n" +
	"\x12OPERATOR_TYPE_CAST\x10\x19\x12\x17\n" +
	"\x13OPERATOR_TYPE_UNION\x10\x1a\x12\x17\n" +
	"\x13OPERATOR_TYPE_ROUTE\x10\x1b\x12\x1a\n" +
	"\x16OPERATOR_TYPE_COALESCE\x10\x1c\x12\x1b\n" +
	"\x17OPERATOR_TYPE_ADD_FIELD\x10\x1d\x12\x1b\n" +
	"\x17OPERATOR_TYPE_AGGREGATE\x10(\x12\x1d\n" +
	"\x19OPERATOR_TYPE_DEDUPLICATE\x10)\x12\x17\n" +
	"\x13OPERATOR_TYPE_TOP_N\x10*\x12\x1f\n" +
	"\x1bOPERATOR_TYPE_TUMBLE_WINDOW\x102\x12\x1e\n" +
	"\x1aOPERATOR_TYPE_SLIDE_WINDOW\x103\x12 \n" +
	"\x1cOPERATOR_TYPE_SESSION_WINDOW\x104\x12\x1b\n" +
	"\x17OPERATOR_TYPE_HASH_JOIN\x10<\x12\x1f\n" +
	"\x1bOPERATOR_TYPE_TEMPORAL_JOIN\x10=\x12\x1d\n" +
	"\x19OPERATOR_TYPE_LOOKUP_JOIN\x10>\x12\x1f\n" +
	"\x1bOPERATOR_TYPE_INTERVAL_JOIN\x10?\x12\x19\n" +
	"\x15OPERATOR_TYPE_RAW_SQL\x10F\x12!\n" +
	"\x1dOPERATOR_TYPE_MATCH_RECOGNIZE\x10G*\x87\x01\n" +
	"\x11ExecutionStrategy\x12\"\n" +
	"\x1eEXECUTION_STRATEGY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fEXECUTION_STRATEGY_ARROW_NATIVE\x10\x01\x12)\n" +
	"%EXECUTION_STRATEGY_DUCKDB_MICRO_BATCH\x10\x02*\x86\x01\n" +
	"\rChangelogMode\x12\x1e\n" +
	"\x1aCHANGELOG_MODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCHANGELOG_MODE_APPEND_ONLY\x10\x01\x12\x1a\n" +
	"\x16CHANGELOG_MODE_RETRACT\x10\x02\x12\x19\n" +
	"\x15CHANGELOG_MODE_UPSERT\x10\x03*\xca\x01\n" +
	"\x0fShuffleStrategy\x12 \n" +
	"\x1cSHUFFLE_STRATEGY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SHUFFLE_STRATEGY_FORWARD\x10\x01\x12\x19\n" +
	"\x15SHUFFLE_STRATEGY_HASH\x10\x02\x12\x1e\n" +
	"\x1aSHUFFLE_STRATEGY_BROADCAST\x10\x03\x12 \n" +
	"\x1cSHUFFLE_STRATEGY_ROUND_ROBIN\x10\x04\x12\x1a\n" +
	"\x16SHUFFLE_STRATEGY_RANGE\x10\x05B?Z=github.com/sandboxws/isotope/runtime/internal/proto/isotopev1b\x06proto3"

var (
	file_isotope_v1_plan_proto_rawDescOnce sync.Once
	file_isotope_v1_plan_proto_rawDescData []byte
)

func file_isotope_v1_plan_proto_rawDescGZIP() []byte {
	file_isotope_v1_plan_proto_rawDescOnce.Do(func() {
		file_isotope_v1_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_isotope_v1_plan_proto_rawDesc), len(file_isotope_v1_plan_proto_rawDesc)))
	})
	return file_isotope_v1_plan_proto_rawDescData
}

var file_isotope_v1_plan_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_isotope_v1_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_isotope_v1_plan_proto_goTypes = []any{
	(PipelineMode)(0),             // 0: isotope.v1.PipelineMode
	(OperatorType)(0),             // 1: isotope.v1.OperatorType
	(ExecutionStrategy)(0),        // 2: isotope.v1.ExecutionStrategy
	(ChangelogMode)(0),            // 3: isotope.v1.ChangelogMode
	(ShuffleStrategy)(0),          // 4: isotope.v1.ShuffleStrategy
	(*ExecutionPlan)(nil),         // 5: isotope.v1.ExecutionPlan
	(*CheckpointConfig)(nil),      // 6: isotope.v1.CheckpointConfig
	(*StateConfig)(nil),           // 7: isotope.v1.StateConfig
	(*RestartConfig)(nil),         // 8: isotope.v1.RestartConfig
	(*SourceLocation)(nil),        // 9: isotope.v1.SourceLocation
	(*OperatorNode)(nil),          // 10: isotope.v1.OperatorNode
	(*Edge)(nil),                  // 11: isotope.v1.Edge
	(*Schema)(nil),                // 12: isotope.v1.Schema
	(*KafkaSourceConfig)(nil),     // 13: isotope.v1.KafkaSourceConfig
	(*GeneratorSourceConfig)(nil), // 14: isotope.v1.GeneratorSourceConfig
	(*KafkaSinkConfig)(nil),       // 15: isotope.v1.KafkaSinkConfig
	(*ConsoleSinkConfig)(nil),     // 16: isotope.v1.ConsoleSinkConfig
	(*FilterConfig)(nil),          // 17: isotope.v1.FilterConfig
	(*MapConfig)(nil),             // 18: isotope.v1.MapConfig
	(*FlatMapConfig)(nil),         // 19: isotope.v1.FlatMapConfig
	(*RenameConfig)(nil),          // 20: isotope.v1.RenameConfig
	(*DropConfig)(nil),            // 21: isotope.v1.DropConfig
	(*CastConfig)(nil),            // 22: isotope.v1.CastConfig
	(*UnionConfig)(nil),           // 23: isotope.v1.UnionConfig
	(*RouteConfig)(nil),           // 24: isotope.v1.RouteConfig
	(*CoalesceConfig)(nil),        // 25: isotope.v1.CoalesceConfig
	(*AddFieldConfig)(nil),        // 26: isotope.v1.AddFieldConfig
	(*AggregateConfig)(nil),       // 27: isotope.v1.AggregateConfig
	(*DeduplicateConfig)(nil),     // 28: isotope.v1.DeduplicateConfig
	(*TopNConfig)(nil),            // 29: isotope.v1.TopNConfig
	(*TumbleWindowConfig)(nil),    // 30: isotope.v1.TumbleWindowConfig
	(*SlideWindowConfig)(nil),     // 31: isotope.v1.SlideWindowConfig
	(*SessionWindowConfig)(nil),   // 32: isotope.v1.SessionWindowConfig
	(*HashJoinConfig)(nil),        // 33: isotope.v1.HashJoinConfig
	(*TemporalJoinConfig)(nil),    // 34: isotope.v1.TemporalJoinConfig
	(*LookupJoinConfig)(nil),      // 35: isotope.v1.LookupJoinConfig
	(*IntervalJoinConfig)(nil),    // 36: isotope.v1.IntervalJoinConfig
	(*RawSQLConfig)(nil),          // 37: isotope.v1.RawSQLConfig
	(*MatchRecognizeConfig)(nil),  // 38: isotope.v1.MatchRecognizeConfig
}
var file_isotope_v1_plan_proto_depIdxs = []int32{
	0,  // 0: isotope.v1.ExecutionPlan.mode:type_name -> isotope.v1.PipelineMode
	6,  // 1: isotope.v1.ExecutionPlan.checkpoint:type_name -> isotope.v1.CheckpointConfig
	7,  // 2: isotope.v1.ExecutionPlan.state:type_name -> isotope.v1.StateConfig
	8,  // 3: isotope.v1.ExecutionPlan.restart:type_name -> isotope.v1.RestartConfig
	10, // 4: isotope.v1.ExecutionPlan.operators:type_name -> isotope.v1.OperatorNode
	11, // 5: isotope.v1.ExecutionPlan.edges:type_name -> isotope.v1.Edge
	1,  // 6: isotope.v1.OperatorNode.operator_type:type_name -> isotope.v1.OperatorType
	12, // 7: isotope.v1.OperatorNode.input_schema:type_name -> isotope.v1.Schema
	12, // 8: isotope.v1.OperatorNode.output_schema:type_name -> isotope.v1.Schema
	3,  // 9: isotope.v1.OperatorNode.changelog_mode:type_name -> isotope.v1.ChangelogMode
	9,  // 10: isotope.v1.OperatorNode.source_location:type_name -> isotope.v1.SourceLocation
	2,  // 11: isotope.v1.OperatorNode.execution_strategy:type_name -> isotope.v1.ExecutionStrategy
	13, // 12: isotope.v1.OperatorNode.kafka_source:type_name -> isotope.v1.KafkaSourceConfig
	14, // 13: isotope.v1.OperatorNode.generator_source:type_name -> isotope.v1.GeneratorSourceConfig
	15, // 14: isotope.v1.OperatorNode.kafka_sink:type_name -> isotope.v1.KafkaSinkConfig
	16, // 15: isotope.v1.OperatorNode.console_sink:type_name -> isotope.v1.ConsoleSinkConfig
	17, // 16: isotope.v1.OperatorNode.filter:type_name -> isotope.v1.FilterConfig
	18, // 17: isotope.v1.OperatorNode.map:type_name -> isotope.v1.MapConfig
	19, // 18: isotope.v1.OperatorNode.flat_map:type_name -> isotope.v1.FlatMapConfig
	20, // 19: isotope.v1.OperatorNode.rename:type_name -> isotope.v1.RenameConfig
	21, // 20: isotope.v1.OperatorNode.drop:type_name -> isotope.v1.DropConfig
	22, // 21: isotope.v1.OperatorNode.cast:type_name -> isotope.v1.CastConfig
	23, // 22: isotope.v1.OperatorNode.union:type_name -> isotope.v1.UnionConfig
	24, // 23: isotope.v1.OperatorNode.route:type_name -> isotope.v1.RouteConfig
	25, // 24: isotope.v1.OperatorNode.coalesce:type_name -> isotope.v1.CoalesceConfig
	26, // 25: isotope.v1.OperatorNode.add_field:type_name -> isotope.v1.AddFieldConfig
	27, // 26: isotope.v1.OperatorNode.aggregate:type_name -> isotope.v1.AggregateConfig
	28, // 27: isotope.v1.OperatorNode.deduplicate:type_name -> isotope.v1.DeduplicateConfig
	29, // 28: isotope.v1.OperatorNode.top_n:type_name -> isotope.v1.TopNConfig
	30, // 29: isotope.v1.OperatorNode.tumble_window:type_name -> isotope.v1.TumbleWindowConfig
	31, // 30: isotope.v1.OperatorNode.slide_window:type_name -> isotope.v1.SlideWindowConfig
	32, // 31: isotope.v1.OperatorNode.session_window:type_name -> isotope.v1.SessionWindowConfig
	33, // 32: isotope.v1.OperatorNode.hash_join:type_name -> isotope.v1.HashJoinConfig
	34, // 33: isotope.v1.OperatorNode.temporal_join:type_name -> isotope.v1.TemporalJoinConfig
	35, // 34: isotope.v1.OperatorNode.lookup_join:type_name -> isotope.v1.LookupJoinConfig
	36, // 35: isotope.v1.OperatorNode.interval_join:type_name -> isotope.v1.IntervalJoinConfig
	37, // 36: isotope.v1.OperatorNode.raw_sql:type_name -> isotope.v1.RawSQLConfig
	38, // 37: isotope.v1.OperatorNode.match_recognize:type_name -> isotope.v1.MatchRecognizeConfig
	4,  // 38: isotope.v1.Edge.shuffle:type_name -> isotope.v1.ShuffleStrategy
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_isotope_v1_plan_proto_init() }
func file_isotope_v1_plan_proto_init() {
	if File_isotope_v1_plan_proto != nil {
		return
	}
	file_isotope_v1_schema_proto_init()
	file_isotope_v1_operators_proto_init()
	file_isotope_v1_plan_proto_msgTypes[5].OneofWrappers = []any{
		(*OperatorNode_KafkaSource)(nil),
		(*OperatorNode_GeneratorSource)(nil),
		(*OperatorNode_KafkaSink)(nil),
		(*OperatorNode_ConsoleSink)(nil),
		(*OperatorNode_Filter)(nil),
		(*OperatorNode_Map)(nil),
		(*OperatorNode_FlatMap)(nil),
		(*OperatorNode_Rename)(nil),
		(*OperatorNode_Drop)(nil),
		(*OperatorNode_Cast)(nil),
		(*OperatorNode_Union)(nil),
		(*OperatorNode_Route)(nil),
		(*OperatorNode_Coalesce)(nil),
		(*OperatorNode_AddField)(nil),
		(*OperatorNode_Aggregate)(nil),
		(*OperatorNode_Deduplicate)(nil),
		(*OperatorNode_TopN)(nil),
		(*OperatorNode_TumbleWindow)(nil),
		(*OperatorNode_SlideWindow)(nil),
		(*OperatorNode_SessionWindow)(nil),
		(*OperatorNode_HashJoin)(nil),
		(*OperatorNode_TemporalJoin)(nil),
		(*OperatorNode_LookupJoin)(nil),
		(*OperatorNode_IntervalJoin)(nil),
		(*OperatorNode_RawSql)(nil),
		(*OperatorNode_MatchRecognize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_isotope_v1_plan_proto_rawDesc), len(file_isotope_v1_plan_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_isotope_v1_plan_proto_goTypes,
		DependencyIndexes: file_isotope_v1_plan_proto_depIdxs,
		EnumInfos:         file_isotope_v1_plan_proto_enumTypes,
		MessageInfos:      file_isotope_v1_plan_proto_msgTypes,
	}.Build()
	File_isotope_v1_plan_proto = out.File
	file_isotope_v1_plan_proto_goTypes = nil
	file_isotope_v1_plan_proto_depIdxs = nil
}
