// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: isotope/v1/schema.proto

package isotopev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Arrow type enum — mirrors the TypeScript ArrowType enum in packages/dsl/src/core/types.ts.
// Values start at 0 (UNSPECIFIED) so the Go zero-value is safe.
type ArrowType int32

const (
	ArrowType_ARROW_TYPE_UNSPECIFIED  ArrowType = 0
	ArrowType_ARROW_TYPE_INT8         ArrowType = 1
	ArrowType_ARROW_TYPE_INT16        ArrowType = 2
	ArrowType_ARROW_TYPE_INT32        ArrowType = 3
	ArrowType_ARROW_TYPE_INT64        ArrowType = 4
	ArrowType_ARROW_TYPE_FLOAT32      ArrowType = 5
	ArrowType_ARROW_TYPE_FLOAT64      ArrowType = 6
	ArrowType_ARROW_TYPE_STRING       ArrowType = 7
	ArrowType_ARROW_TYPE_BINARY       ArrowType = 8
	ArrowType_ARROW_TYPE_BOOLEAN      ArrowType = 9
	ArrowType_ARROW_TYPE_TIMESTAMP_MS ArrowType = 10
	ArrowType_ARROW_TYPE_TIMESTAMP_US ArrowType = 11
	ArrowType_ARROW_TYPE_DATE32       ArrowType = 12
	ArrowType_ARROW_TYPE_DECIMAL128   ArrowType = 13
	ArrowType_ARROW_TYPE_LIST         ArrowType = 14
	ArrowType_ARROW_TYPE_MAP          ArrowType = 15
	ArrowType_ARROW_TYPE_STRUCT       ArrowType = 16
)

// Enum value maps for ArrowType.
var (
	ArrowType_name = map[int32]string{
		0:  "ARROW_TYPE_UNSPECIFIED",
		1:  "ARROW_TYPE_INT8",
		2:  "ARROW_TYPE_INT16",
		3:  "ARROW_TYPE_INT32",
		4:  "ARROW_TYPE_INT64",
		5:  "ARROW_TYPE_FLOAT32",
		6:  "ARROW_TYPE_FLOAT64",
		7:  "ARROW_TYPE_STRING",
		8:  "ARROW_TYPE_BINARY",
		9:  "ARROW_TYPE_BOOLEAN",
		10: "ARROW_TYPE_TIMESTAMP_MS",
		11: "ARROW_TYPE_TIMESTAMP_US",
		12: "ARROW_TYPE_DATE32",
		13: "ARROW_TYPE_DECIMAL128",
		14: "ARROW_TYPE_LIST",
		15: "ARROW_TYPE_MAP",
		16: "ARROW_TYPE_STRUCT",
	}
	ArrowType_value = map[string]int32{
		"ARROW_TYPE_UNSPECIFIED":  0,
		"ARROW_TYPE_INT8":         1,
		"ARROW_TYPE_INT16":        2,
		"ARROW_TYPE_INT32":        3,
		"ARROW_TYPE_INT64":        4,
		"ARROW_TYPE_FLOAT32":      5,
		"ARROW_TYPE_FLOAT64":      6,
		"ARROW_TYPE_STRING":       7,
		"ARROW_TYPE_BINARY":       8,
		"ARROW_TYPE_BOOLEAN":      9,
		"ARROW_TYPE_TIMESTAMP_MS": 10,
		"ARROW_TYPE_TIMESTAMP_US": 11,
		"ARROW_TYPE_DATE32":       12,
		"ARROW_TYPE_DECIMAL128":   13,
		"ARROW_TYPE_LIST":         14,
		"ARROW_TYPE_MAP":          15,
		"ARROW_TYPE_STRUCT":       16,
	}
)

func (x ArrowType) Enum() *ArrowType {
	p := new(ArrowType)
	*p = x
	return p
}

func (x ArrowType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArrowType) Descriptor() protoreflect.EnumDescriptor {
	return file_isotope_v1_schema_proto_enumTypes[0].Descriptor()
}

func (ArrowType) Type() protoreflect.EnumType {
	return &file_isotope_v1_schema_proto_enumTypes[0]
}

func (x ArrowType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArrowType.Descriptor instead.
func (ArrowType) EnumDescriptor() ([]byte, []int) {
	return file_isotope_v1_schema_proto_rawDescGZIP(), []int{0}
}

// A single field within a schema.
type SchemaField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The Flink-style type string (e.g., "BIGINT", "TIMESTAMP(3)", "ARRAY<STRING>").
	FlinkType string    `protobuf:"bytes,2,opt,name=flink_type,json=flinkType,proto3" json:"flink_type,omitempty"`
	ArrowType ArrowType `protobuf:"varint,3,opt,name=arrow_type,json=arrowType,proto3,enum=isotope.v1.ArrowType" json:"arrow_type,omitempty"`
	Nullable  bool      `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"`
	// For DECIMAL: precision and scale.
	Precision int32 `protobuf:"varint,5,opt,name=precision,proto3" json:"precision,omitempty"`
	Scale     int32 `protobuf:"varint,6,opt,name=scale,proto3" json:"scale,omitempty"`
	// For LIST/MAP/STRUCT: nested field definitions.
	Children      []*SchemaField `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaField) Reset() {
	*x = SchemaField{}
	mi := &file_isotope_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaField) ProtoMessage() {}

func (x *SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaField.ProtoReflect.Descriptor instead.
func (*SchemaField) Descriptor() ([]byte, []int) {
	return file_isotope_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaField) GetFlinkType() string {
	if x != nil {
		return x.FlinkType
	}
	return ""
}

func (x *SchemaField) GetArrowType() ArrowType {
	if x != nil {
		return x.ArrowType
	}
	return ArrowType_ARROW_TYPE_UNSPECIFIED
}

func (x *SchemaField) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *SchemaField) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *SchemaField) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *SchemaField) GetChildren() []*SchemaField {
	if x != nil {
		return x.Children
	}
	return nil
}

// Watermark configuration for event-time processing.
type WatermarkConfig struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Column string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	// SQL expression for the watermark (e.g., "ts - INTERVAL '5' SECOND").
	Expression    string `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermarkConfig) Reset() {
	*x = WatermarkConfig{}
	mi := &file_isotope_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermarkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermarkConfig) ProtoMessage() {}

func (x *WatermarkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermarkConfig.ProtoReflect.Descriptor instead.
func (*WatermarkConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *WatermarkConfig) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *WatermarkConfig) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

// Primary key declaration for a schema.
type PrimaryKeyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimaryKeyConfig) Reset() {
	*x = PrimaryKeyConfig{}
	mi := &file_isotope_v1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryKeyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryKeyConfig) ProtoMessage() {}

func (x *PrimaryKeyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryKeyConfig.ProtoReflect.Descriptor instead.
func (*PrimaryKeyConfig) Descriptor() ([]byte, []int) {
	return file_isotope_v1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *PrimaryKeyConfig) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Complete schema definition for an operator's input or output.
type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*SchemaField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Watermark     *WatermarkConfig       `protobuf:"bytes,2,opt,name=watermark,proto3" json:"watermark,omitempty"`
	PrimaryKey    *PrimaryKeyConfig      `protobuf:"bytes,3,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_isotope_v1_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_isotope_v1_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_isotope_v1_schema_proto_rawDescGZIP(), []int{3}
}

func (x *Schema) GetFields() []*SchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Schema) GetWatermark() *WatermarkConfig {
	if x != nil {
		return x.Watermark
	}
	return nil
}

func (x *Schema) GetPrimaryKey() *PrimaryKeyConfig {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

var File_isotope_v1_schema_proto protoreflect.FileDescriptor

const file_isotope_v1_schema_proto_rawDesc = "" +
	"\n" +
	"\x17isotope/v1/schema.proto\x12\n" +
	"isotope.v1\"\xfb\x01\n" +
	"\vSchemaField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"flink_type\x18\x02 \x01(\tR\tflinkType\x124\n" +
	"\n" +
	"arrow_type\x18\x03 \x01(\x0e2\x15.isotope.v1.ArrowTypeR\tarrowType\x12\x1a\n" +
	"\bnullable\x18\x04 \x01(\bR\bnullable\x12\x1c\n" +
	"\tprecision\x18\x05 \x01(\x05R\tprecision\x12\x14\n" +
	"\x05scale\x18\x06 \x01(\x05R\x05scale\x123\n" +
	"\bchildren\x18\a \x03(\v2\x17.isotope.v1.SchemaFieldR\bchildren\"I\n" +
	"\x0fWatermarkConfig\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\",\n" +
	"\x10PrimaryKeyConfig\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\"\xb3\x01\n" +
	"\x06Schema\x12/\n" +
	"\x06fields\x18\x01 \x03(\v2\x17.isotope.v1.SchemaFieldR\x06fields\x129\n" +
	"\twatermark\x18\x02 \x01(\v2\x1b.isotope.v1.WatermarkConfigR\twatermark\x12=\n" +
	"\vprimary_key\x18\x03 \x01(\v2\x1c.isotope.v1.PrimaryKeyConfigR\n" +
	"primaryKey*\xa0\x03\n" +
	"\tArrowType\x12\x1a\n" +
	"\x16ARROW_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fARROW_TYPE_INT8\x10\x01\x12\x14\n" +
	"\x10ARROW_TYPE_INT16\x10\x02\x12\x14\n" +
	"\x10ARROW_TYPE_INT32\x10\x03\x12\x14\n" +
	"\x10ARROW_TYPE_INT64\x10\x04\x12\x16\n" +
	"\x12ARROW_TYPE_FLOAT32\x10\x05\x12\x16\n" +
	"\x12ARROW_TYPE_FLOAT64\x10\x06\x12\x15\n" +
	"\x11ARROW_TYPE_STRING\x10\a\x12\x15\n" +
	"\x11ARROW_TYPE_BINARY\x10\b\x12\x16\n" +
	"\x12ARROW_TYPE_BOOLEAN\x10\t\x12\x1b\n" +
	"\x17ARROW_TYPE_TIMESTAMP_MS\x10\n" +
	"\x12\x1b\n" +
	"\x17ARROW_TYPE_TIMESTAMP_US\x10\v\x12\x15\n" +
	"\x11ARROW_TYPE_DATE32\x10\f\x12\x19\n" +
	"\x15ARROW_TYPE_DECIMAL128\x10\r\x12\x13\n" +
	"\x0fARROW_TYPE_LIST\x10\x0e\x12\x12\n" +
	"\x0eARROW_TYPE_MAP\x10\x0f\x12\x15\n" +
	"\x11ARROW_TYPE_STRUCT\x10\x10B?Z=github.com/sandboxws/isotope/runtime/internal/proto/isotopev1b\x06proto3"

var (
	file_isotope_v1_schema_proto_rawDescOnce sync.Once
	file_isotope_v1_schema_proto_rawDescData []byte
)

func file_isotope_v1_schema_proto_rawDescGZIP() []byte {
	file_isotope_v1_schema_proto_rawDescOnce.Do(func() {
		file_isotope_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_isotope_v1_schema_proto_rawDesc), len(file_isotope_v1_schema_proto_rawDesc)))
	})
	return file_isotope_v1_schema_proto_rawDescData
}

var file_isotope_v1_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_isotope_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_isotope_v1_schema_proto_goTypes = []any{
	(ArrowType)(0),           // 0: isotope.v1.ArrowType
	(*SchemaField)(nil),      // 1: isotope.v1.SchemaField
	(*WatermarkConfig)(nil),  // 2: isotope.v1.WatermarkConfig
	(*PrimaryKeyConfig)(nil), // 3: isotope.v1.PrimaryKeyConfig
	(*Schema)(nil),           // 4: isotope.v1.Schema
}
var file_isotope_v1_schema_proto_depIdxs = []int32{
	0, // 0: isotope.v1.SchemaField.arrow_type:type_name -> isotope.v1.ArrowType
	1, // 1: isotope.v1.SchemaField.children:type_name -> isotope.v1.SchemaField
	1, // 2: isotope.v1.Schema.fields:type_name -> isotope.v1.SchemaField
	2, // 3: isotope.v1.Schema.watermark:type_name -> isotope.v1.WatermarkConfig
	3, // 4: isotope.v1.Schema.primary_key:type_name -> isotope.v1.PrimaryKeyConfig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_isotope_v1_schema_proto_init() }
func file_isotope_v1_schema_proto_init() {
	if File_isotope_v1_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_isotope_v1_schema_proto_rawDesc), len(file_isotope_v1_schema_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_isotope_v1_schema_proto_goTypes,
		DependencyIndexes: file_isotope_v1_schema_proto_depIdxs,
		EnumInfos:         file_isotope_v1_schema_proto_enumTypes,
		MessageInfos:      file_isotope_v1_schema_proto_msgTypes,
	}.Build()
	File_isotope_v1_schema_proto = out.File
	file_isotope_v1_schema_proto_goTypes = nil
	file_isotope_v1_schema_proto_depIdxs = nil
}
